### PR TITLE
Fix mac travis

### PR DESCRIPTION
**Pull request by zbeekman**
[links]:#
[contributing guidelines]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md
[issue]: https://github.com/sourceryinstitute/OpenCoarrays/issues
[PR response img]: https://img.shields.io/issuestats/p/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square
[coverage]: https://img.shields.io/codecov/c/github/sourceryinstitute/OpenCoarrays/master.svg?style=flat-square

|  Avg response time                |  coverage on master         |
|:---------------------------------:|:---------------------------:|
| ![Issue Stats][PR response img]   | ![Codecov branch][coverage] |

## Summary of changes ##

- Updated build matrix to use more recent compilers.
- Fixed<sup>*</sup> macOS Travis-CI builds.
- Updated CMakeLists.txt to be more modern, replace almost all instances of:
  1. `include_directories()`
  2. `add_definitions()`
  3. `add_compile_options()`
  4. `link_directories()`
  5. `link_libraries()`
- These get replaced with per-target commands that specify the scope of the library, include path, library path, compiler flag, or definition. (The scopes are `PUBLIC`: use for the target and transitively propagate, `PRIVATE`: just use for the target, don't propagate and `INTERFACE`: don't use for this target, but transitively propagate to consumers.

## Rationale for changes ##

We want better support for `find_package(OpenCoarrays)` so that consumers can `target_link_libraries(my_caf_program PUBLIC OpenCoarrays)`. Also we want the build matrix to work.

## Additional info and certifications ##

This pull request (PR) is a:

- [X] Bug fix
- [X] Feature addition
- [ ] Other, Please describe:

### I certify that ###

- [X] I reviewed and followed the [contributing guidelines], including
      - Increasing test coverage for all feature-addition PRs
      - Increasing test coverage for all bug-fix PRs for which there
        does not already exist a related test that failed before the PR
      - At least maintaining test coverage for all other PRs
      - Ensuring that all tests pass when run locally 
      - Naming PR  to indicate work in progress (WIP) and to attach the PR
        to the appropriate bug report or feature request [issue]
      - White space (no trailing white space or white space errors may
        be introduced)
      - Commenting code where it is non-obvious and non-trivial
      - Logically atomic, self consistent and coherent commits
      - Commit message content
      - Waiting 24 hours before self-approving the PR to give another
        OpenCoarrays developer a chance to review my proposed code

### CODE REVIEW

**Comment by rouson** [comment]
LGTM

**Comment by zbeekman** [comment]
LGTM

**Comment by zbeekman** [comment]
@rouson Pullapprove is taking longer than normal, but it gets there in the end. Also, I have it setup so that CI stuff needs my approval when it's edited. (Approval from ConfigManagers group.)

**Comment by zbeekman** [comment]
LGTM

**Comment by zbeekman** [comment]
LGTM

Merging this even though there is more work on this branch towards #605 that I would like to do. This will at least get OSX CI working again untill we can resolve the FindMPI woes on travis-ci with brewed MPI.

**Pull request merged**
