### PR TITLE
Fix setup sh script

### PR DESCRIPTION
**Pull request by rouson**

### CODE REVIEW

**Comment by zbeekman** [comment]
This is an example of where an interactive rebase to squash these two commits together would make sense... I'd be happy to do it myself or we can do it on our call.

**Comment by rouson** [comment]
You're welcome to do it.  I certainly thought of it and would have done it if I remembered how, but the benefit didn't seem to outweigh the cost. Nonetheless, I'm not against the idea.  Feel free to squash away. :)

**Comment by zbeekman** [comment]
Once tests pass, should be ready to merge

**Comment by zbeekman** [comment]
:zap:

**Pull request merged**
