### PR TITLE
Issue 700 enable multi allocatable arrays

### LINKED ISSUE #700: RFE: support nested allocatable derived-type array components inside derived-type coarrays
The transcript below demonstrates the runtime error message that the OpenCoarrays function `libcaf_mpi::caf_get_by_ref()` produces in a simple scenario wherein a derived-type coarray has an `allocatable`, derived-type array component.   A cumbersome workaround is to flatten such coarray data structures so that the components of derived type coarrays are intrinsic types.  Even with this workaround, a `source` allocation will fail.  A workaround for the lack of `source` allocation is to use `mold` allocation followed by _element-by-element_ copying of the component array.

The following are the results of compiling the code below with the `gfortran` versions cited in bold:
- **8.3.0:** the final allocation generates the runtime error message below.
- **9.2.0:** the allocation completes without error but the subsequent component access generates a `segmentation fault - invalid memory reference`.
- **10.0.0:** same as 8.3.0.

```bash
$ cat opencoarrays-missing-feature.f90 
```
```fortran
  implicit none

  type package
    integer, allocatable :: surface_fluxes(:)
  end type

  type outbox
    type(package), allocatable :: block_surfaces(:)
  end type

  type(outbox), save :: halo[*]

  integer, parameter :: source_image = 1
  integer, parameter :: message(1)=[99]

  if (this_image() == source_image) then
    allocate(halo%block_surfaces(1))
    allocate(halo%block_surfaces(1)%surface_fluxes, source = message)
  end if

  sync all

  if (this_image() /= source_image) then
    allocate(halo%block_surfaces(1))
    allocate(halo%block_surfaces(1)%surface_fluxes, mold = halo[source_image]%block_surfaces(1)%surface_fluxes)
    halo%block_surfaces(1)%surface_fluxes(1) = halo[source_image]%block_surfaces(1)%surface_fluxes(1)
  end if

end
```
```
$ caf opencoarrays-missing-feature.f90 

$ cafrun -n 2 ./a.out
Fortran runtime error on image 2: libcaf_mpi::caf_get_by_ref(): two or more array part references are not supported.

Error: Command:
   `/usr/local/Cellar/mpich-3.2-gnu-8.3.0/bin/mpiexec -n 2 ./a.out`
failed to run.
```

### PR DESCRIPTION
**Pull request by vehre**
[links]:#
[contributing guidelines]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md
[issue]: https://github.com/sourceryinstitute/OpenCoarrays/issues
[coverage]: https://img.shields.io/codecov/c/github/sourceryinstitute/OpenCoarrays/master.svg?style=flat-square

|  coverage on master         |
|:---------------------------:|
| ![Codecov branch][coverage] |

## Summary of changes ##

Fixing issue-511 correctly. Adding ability to really use global dynamic window. Change to fine granular mandatory locking.

## Rationale for changes ##

The pull reQuest is split into several commits, to simplify review. The most interesting one is the last one.

The initial fix for issue #511 while seeming effective did not work when more than one scalar array-reference was present in the references of a coarray. The last commit fixes this by dedicatedly analysing the array references and not relying on the reallocation flag, but using its own notion to figure error situations.

Furthermore had the way of locking dedicated windows and the global dynamic one by changed to a fine granular and near access locking. I.e. each MPI_Get or _Put is now encased in the appropriate lock and unlock calls. Only this made using the global dynamic window possible which then fixed #700 . At least with mpich 3.3.2. OpenMPI 4.0.2 still has several regressions, that are not understandable.

## Additional info and certifications ##

This pull request (PR) is a:

- [x] Bug fix
- [x] Feature addition
- [ ] Other, Please describe:

### I certify that ###

- [x] I certify that:
  - I have reviewed and followed the [contributing guidelines]
  - I will wait at least 24 hours before self-approving the PR to give another
    OpenCoarrays developer a chance to review my proposed code
  - I have not introduced errant white space (no trailing white space or white space errors may
    be introduced)
  - I have added an explanation of what these changes do and why they should be included
  - I have checked to ensure there aren't other open [Pull Requests] for the same change
  - I have you written new tests for these changes
  - I have successfully tested these changes locally
  - I have commented any non-trivial, non-obvious code changes
  - The commits are logically atomic, self consistent and coherent
  - The [commit messages] follow [best practices]
  - Test coverage is maintained or increased after this is merged

## Code coverage data

coverage on master

[links]: #
[best practices]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[commit messages]: https://thoughtbot.com/blog/5-useful-tips-for-a-better-commit-message
[Pull Requests]: https://github.com/sourceryinstitue/OpenCoarrays/pulls

### CODE REVIEW

**Comment by rouson** [comment]
@vehre thanks for this PR.  I think it's safe to merge so I'll do so shortly.  Alessarndo took a look at it for me and passed along the following question: "Why did you use MPI_Win_lock instead of a combination of MPI_Win_lockall and MPI_Win_Flush?"

**Comment by vehre** [comment]
Hi Damian,
I used win_lock and win_unlock instead of unlockall and flush, because only
the former worked for me while the latter lead to deadlocks. And that works
only with mpich and not with openmpi. I am happy to learn different working
approaches, but I only found that one working.

Regards,
Andre


Am 25. September 2020 17:09:54 schrieb Damian Rouson
<notifications@github.com>:

**Comment by rouson** [comment]
@vehre I see that there's a conflict showing on this PR.  Presumably that's because one or more PR's were merged into master since this PR branched off of master.  It appears the conflict is trivial so I'll see if I can resolve it and then rerun the tests later today or this weekend.  If you happen to get to it first, let me know.

**Comment by vehre** [comment]
I am sorry, I can't take a look before Sunday afternoon. I have no computer
to my disposal currently.
Am 25. September 2020 21:25:08 schrieb Damian Rouson
<notifications@github.com>:

**Comment by vehre** [comment]
Resolved the merge conflict.

**Comment by rouson** [comment]
@vehre I see that you resolved the merge conflict.  I just tested locally on macOS and all tests pass.  I'll wait for the Linux tests to pass on Travis CI and then merge.  I think something is wrong with the macOS tests on Travis CI so I'll ignore any failures there.  I think we'll transition soon to using GitHub's CI capabilities, which might resolve the issue.

**Pull request merged**
