### PR TITLE
Propagate license and install.sh fixes to devel

### PR DESCRIPTION
**Pull request by zbeekman**

### CODE REVIEW

**Comment by zbeekman** [comment]
:shipit:

**Comment by rouson** [comment]
@zbeekman Should this be closed now that you did the merge by hand?

**Comment by zbeekman** [comment]
This is to apply changes from master to devel. When merging by hand the pull request will be closed after you push. I have yet to merge this, but I'll do it now.

**Comment by zbeekman** [comment]
merged in 72a6000a4caea8643844d9e6302abbfbefbd281c

**Comment by zbeekman** [comment]
> When merging by hand the pull request will be closed after you push.

I guess this may depend on whether there are merge conflicts, and how they are resolved. For some reason the auto-close didn't work this time but it has in the past.

**Pull request closed without merging**
