### PR TITLE
Revert the commits of PR #611

### PR DESCRIPTION
**Pull request by MichaelSiehl**
[links]:#
[contributing guidelines]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md
[issue]: https://github.com/sourceryinstitute/OpenCoarrays/issues
[PR response img]: https://img.shields.io/issuestats/p/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square
[coverage]: https://img.shields.io/codecov/c/github/sourceryinstitute/OpenCoarrays/master.svg?style=flat-square

|  Avg response time                |  coverage on master         |
|:---------------------------------:|:---------------------------:|
| ![Issue Stats][PR response img]   | ![Codecov branch][coverage] |

## Summary of changes ##
Revert from the changes of PR #611 
Summarize what you changed
Reverting the commits of PR #611.
## Rationale for changes ##
The rationale for the changes of PR #611 does contain severe mistakes.
Why did you make these changes?
The rationale for the changes of PR #611 does contain severe mistakes.
## Additional info and certifications ##
See this corrected version of the original program teams_subset, which is the rationale behind PR #611:
```fortran
program mistake_in_teams_subset
  use iso_fortran_env, only : team_type
  implicit none

  type(team_type) :: team
  integer :: initial_team_image, max_image(2), min_image(2), myteam

  initial_team_image = this_image()

  if (initial_team_image == 1 .or. initial_team_image == num_images()) then
    myteam = 1
  else
    myteam = 2
  end if

  form team (myteam, team)

  write(*,*) 'team number is:', team_number() ! output is -1, because we are still in the initial team
!  if (myteam == 1) then ! if we would do this, we would execute the following CHANGE TEAM statement
                         ! on only a subset of the images of the current (initial) team, resulting
                         ! in a synchronization failure or deadlock. (This is the main mistake
                         ! of the original teams_subset.f90 example program).
  if (team_number() == 1) then ! which is not the case thus,
    change team(team) ! will not be executed, but at least there is no deadlock any more.
      max_image = [initial_team_image, this_image()]
      call co_max(max_image)
      min_image = [initial_team_image, this_image()]
      call co_min(min_image)
    end team
    if (any(min_image /= [1, 1]) .or. any(max_image /= [num_images(), 2])) then
      write(*,*) "Test failed."
      error stop
    end if
  end if

  sync all

  if (initial_team_image == 1) write(*,*) "Test passed."

end program
```
This pull request (PR) is a:

- [x] Bug fix
- [ ] Feature addition
- [ ] Other, Please describe:

### I certify that ###

- [x] I reviewed and followed the [contributing guidelines], including
      - Increasing test coverage for all feature-addition PRs
      - Increasing test coverage for all bug-fix PRs for which there
        does not already exist a related test that failed before the PR
      - At least maintaining test coverage for all other PRs
      - Ensuring that all tests pass when run locally 
      - Naming PR  to indicate work in progress (WIP) and to attach the PR
        to the appropriate bug report or feature request [issue]
      - White space (no trailing white space or white space errors may
        be introduced)
      - Commenting code where it is non-obvious and non-trivial
      - Logically atomic, self consistent and coherent commits
      - Commit message content
      - Waiting 24 hours before self-approving the PR to give another
        OpenCoarrays developer a chance to review my proposed code

### CODE REVIEW

**Comment by MichaelSiehl** [comment]
We have an ongoing discussion about this in #610 .

**Comment by MichaelSiehl** [comment]
@rouson: Originally, I did revert the changes in `mpi_caf.c`. But I do not understand the effects or possible side-effects of these changes. Thus, I must leave it to you (or others) to decide if these changes should be reverted. (I did submit this PR because you did explicitly ask for it).

Also, it seems I did fail to convince @nathanweeks that his original code example may not conform with the Fortran 2018 standard. On the other hand, if the Fortran standard would allow such a code example, I can't see how this could ever execute in a manner the programmer does expect it. 

Best Regards

**Comment by nathanweeks** [comment]
Heee's a different reproducer (where all active images in the initial team call CHANGE TEAM) that illustrates the synchronization effects of CHANGE TEAM that PR #611 attempts to fix to be aligned with the Fortran 2018 standard, specifically:

> **NOTE 11.6**
> Execution of a CHANGE TEAM statement includes a synchronization of the executing image with the other images that will be in the same team after execution of the CHANGE TEAM statement. Synchronization of these images occurs again when the corresponding END TEAM statement is executed.
>
> If it is desired to synchronize all of the images in the team that was current when the CHANGE TEAM statement was executed, a SYNC TEAM statement that specifies the parent team can be executed immediately after the CHANGE TEAM statement. If similar semantics are desired following the END TEAM statement, a SYNC ALL statement could immediately follow the END TEAM statement. 

In this code, the images that will be in team number 1 sleep for 5 seconds (this code assumes the availability of the gfortran `sleep()` extension), then execute CHANGE TEAM. Images that will be in team number 2 immediately call CHANGE TEAM; however, using OpenCoarrays 2.3.1, CHANGE TEAM takes ~5 seconds to complete, as the images that will be on team 2 are synchronizing with all images of the current team (including images that will be on team 1, who first executing `sleep(5)`), rather than the "other images that will be in the same team after execution of the CHANGE TEAM statement". Similarly for END TEAM (this time with team #2 executing `sleep(5)).

```
program teams_sleep
   use iso_fortran_env, only : team_type
   implicit none

   type(team_type) :: team
   integer :: myteam, t_start(2), t_end(2)
   real :: count_rate, t_change_team_min(2), t_change_team_max(2)

   myteam = merge(1, 2, this_image() <= num_images() / 2)
   form team (myteam, team)

   if (myteam == 1) call sleep(5)

   call system_clock(count=t_start(1), count_rate=count_rate)
   change team(team)
      call system_clock(t_end(1))
      if (team_number() == 2) call sleep(5)
      call system_clock(t_start(2))
   end team
   call system_clock(t_end(2))

   change team(team)
      t_change_team_min = (t_end - t_start) / count_rate
      t_change_team_max = t_change_team_min
      call co_min(t_change_team_min, result_image=1)
      call co_max(t_change_team_max, result_image=1)
      if (this_image() == 1) write(*,*) team_number(), t_change_team_min, t_change_team_max
   end team
end program
```

Here's the output using OpenCoarrays 2.3.1:
```
$ cafrun -np 32 ./a.out 
           1   0.00000000       5.00699997       1.00000005E-03   5.00799990    
           2   5.00600004       2.00000009E-03   5.00699997       3.00000003E-0
```

where:
column 1: team_number() within the CHANGE TEAM construct
column 2: minimum CHANGE TEAM statement time among all images in the team
column 3: minumum END TEAM statement time took among all images in the team
column 4: maximum CHANGE TEAM statement time among all images in the team
column 5: maximum END TEAM statement time among all images in the team

With PR #611, during the CHANGE TEAM and END TEAM statements, each image synchronizes only with other images that will be in the same team within the CHANGE TEAM construct:
```
$ cafrun -np 32 ./a.out
           1   1.00000005E-03   2.00000009E-03   3.00000003E-03   3.00000003E-03
           2   0.00000000       3.00000003E-03   1.00000005E-03   3.00000003E-03
```
This reproducer doesn't prove PR #611 is correct, but illustrates the synchronization performance problem it attempts to solve. Because of the way PR #611 is implemented, it also happens to remove the deadlock for the code in issue #610 (correctness of that code is still TBD). If this reproducer is deemed correct, it could be modified to emit pass or fail based on some time threshold.

**Comment by MichaelSiehl** [comment]
@nathanweeks Thanks for providing this. I will try to check soon myself.
Best Regards

**Comment by rouson** [comment]
@MichaelSiehl @nathanweeks For now, it seems that there's no consensus that there's a problem with the library.  The suggested new test above could be added if we add some introspection in the CMake scripts to check whether the `sleep()` function is available and disable the test when it's not.  @nathanweeks If you think that's worthwhile, let us know.  Otherwise, I'm margin this as "wont fix" for now and closing it.  Feel free to reopen it if there's more ongoing discussion or if you want the new test added.

**Comment by MichaelSiehl** [comment]
@rouson: I agree. 
Apart from this, I plan to implement some simple test cases for checking the synchronization capabilities of the CHANGE TEAM construct. I will inform you in case I'd find any problems with the library.
Best Regards

**Pull request closed without merging**
