### PR TITLE
Adding the gitkeep.sh script that writes empty ".gitkeep" files at th…

### PR DESCRIPTION
**Pull request by rouson**
…e branch ends of empty subdirectories.

Committing the otherwise empty doc/dependency_tree/opencoarrays after applyging gitkeep.sh to it.

Signed-off-by: Damian Rouson <damian@rouson.net>

### CODE REVIEW

**Comment by zbeekman** [comment]
Looks good to me :+1:

**Comment by rouson** [comment]
So "All checks have passed" means the Travis-CI tests completed successfully, correct?  Way cool stuff! :D

**Comment by rouson** [comment]
Now this message is incredibly confusing: 

"Pull request successfully merged and closed
You’re all set—the rouson:branch-1.0.0 branch can be safely deleted."

Why the heck does that mean?  Why would I want to delete a branch?

**Comment by zbeekman** [comment]
It's talking about the branch on your fork.... You can safely ignore it, it operates under the assumption you created a new feature branch (or hot-fix branch etc.) on your fork for the purpose of contributing the PR and that once the hot-fix is applied or the feature added (i.e., PR accepted) you will no longer need it (and just create a new one for the next contribution). I'm going to bed now but I'll try to link GitHub's take on the ideal workflow in the AM.

**Comment by rouson** [comment]
Phew... I'm glad I didn't delete it then.  I tried that once before and got burned, but didn't know why it would have ever recommended that I delete the branch anyway.  I think git should be treated like experimental laboratories: there should be a required safety course before anyone gets to touch anything. :O

**Comment by zbeekman** [comment]
It would only delete the branch on your fork's remote, which GitHub provides a means of undoing. In addition it will live on in your fork's local repository, and the local refs (until a prune is requested when fetching or pulling). It only refers to your fork (Rouson/opencoarrays) so it will live on as well on the sourceryinstitute/opencoarrays remote.

**Comment by zbeekman** [comment]
Oh and probably will still exist in your reflog too, at least until a lot of time&history has passed and you request git to do some garbage collection. With git you can always info your mistakes, it's just that it's nearly impossible to figure out how. :pray:

**Pull request merged**
