### PR TITLE
Get pre "allocatable components" updates from master, supersedes #178

### PR DESCRIPTION
**Pull request by zbeekman**
Merge master up to where the work for GCC 7 and coarray allocatable components starts.

This supersedes pull request #178 which will remain closed until the allocatable component work is finished.

### CODE REVIEW

**Comment by zbeekman** [comment]
These conflicts are easy to fix on the command line... I may create a testing branch and do the merge and push it to get the CI tests to run.

**Comment by zbeekman** [comment]
Here is the current CI status of the tests after merge: [Build Status](https://travis-ci.org/sourceryinstitute/opencoarrays/builds/180771157)

Also, no idea why Travis-CI didn't trigger a PR build...

**Comment by zbeekman** [comment]
@afanfa not urgent, but it might be nice to merge in the work up until the allocatable components work started at some point, which is what this PR does. I'm hesitant to merge it without you being able to take a look at it first.

**Comment by afanfa** [comment]
I'm on it.

**Comment by zbeekman** [comment]
Thanks @afanfa!

Also, we need your review on #261 to merge Andre's changes. I had hoped to get his most recent commits cherry picked onto a new branch, where I update the CMake script to only call the new tests if GCC >= 7 and add some tests to the CI infrastructure to verify that these work. If you could take a look at the changes, do whatever local testing you want, and let us know what you think of them (without merging quite yet) that would be much appreciated!

Thanks!

**Comment by zbeekman** [comment]
@afanfa once you've looked at this, just add a `looks good to me` at the beginning of a line in your comment and I'll merge it... or you can even merge it since there are no more conflicts...

**Comment by zbeekman** [comment]
I'm going to close this PR because it looks like we may be abandoning the devel branch.

**Pull request closed without merging**
