### PR TITLE
Boilerplate install.sh/build.sh; add "install.sh -p ofp" option

### PR DESCRIPTION
**Pull request by rouson**
This completes the refactoring of install.sh and its supporting script build.sh so that both now use bash3boilerplate to achieve more sophisticated argument parsing and more robust execution and so that  build.sh replaces the previous "build" script.  Additionally, "install.sh -p ofp" now results in install.sh invoking the new install-ofp.sh script to install the Open Fortran Parser (which currently installs binary files that work only on OS X and only when the prerequisites are placed in /opt). 

With the exception of the "--with-..." arguments and the -n argument, the arguments now work as advertised in the "install.sh -h" output:

  -c --with-c [arg]           Use specified C compiler. Default="gcc"
  -C --with-cxx [arg]         Use specified C++ compiler. Default="g++"
  -d --debug                  Enable debug mode.
  -D --print-downloader [arg] Print download program for package specified in argument.
  -e --verbose                Enable verbose mode, print script as it is executed.
  -f --with-fortran [arg]     Use specified Fortran compiler. Default="gfortran"
  -h --help                   Print this page.
  -i --install-dir [arg]      Install package in specified path. Default="${OPENCOARRAYS_SRC_DIR}/prerequisites/installations/"
  -I --install-version [arg]  Install package version. 
  -j --num-threads [arg]      Number of threads to use when invoking make. Default="1"
  -l --list-packages          Print packages this script can install.
  -m --with-cmake [arg]       Use specified CMake installation. Default="cmake"
  -M --with-mpi [arg]         Use specified MPI installation. Default="mpif90"
  -n --no-color               Disable color output. 
  -p --package [arg]          Install specified package. Default="opencoarrays"
  -P --print-path [arg]       Print installation directory for specified package. 
  -U --print-url [arg]        Print download location for specified package. 
  -v --version                Print OpenCoarrays version number.
  -V --print-version [arg]    Print version number for specified package. Next steps will involve more

### CODE REVIEW

**Comment by zbeekman** [comment]
@rouson can I rebase this on top of the latest commits I added to master? I'd like to see what happens when the codecov.yml file is taken into account.

**Comment by rouson** [comment]
@zbeekman go for it.

**Comment by zbeekman** [comment]
LGTM

**Comment by zbeekman** [comment]
Codecov.io is kinda broken since their upgrade. All important tests have passed, and I'm going to merge...

**Pull request merged**
