### PR TITLE
Support building shared libs

### LINKED ISSUE #245: RFE: Support building shared libraries
Attempting to build shared libraries results in:
```
CMake Error at src/mpi/CMakeLists.txt:27 (install):
  install TARGETS given no LIBRARY DESTINATION for shared library target
  "caf_mpi".
```
Is there a specific reason that this isn't supported?

### PR DESCRIPTION
**Pull request by zbeekman**
Fixes #245

### CODE REVIEW

**Comment by zbeekman** [comment]
LGTM

@apoplawski if you have a chance to check this out and ensure it suits your needs, please do so. Cheers!

**Comment by zbeekman** [comment]
LGTM

**Comment by opoplawski** [comment]
You almost certainly do not want to set the SOVERSION to be based on the project version, but instead start it at 0 and increment it only when breaking ABI compatibility.

**Comment by zbeekman** [comment]
@opoplawski: ah here is the comment I was looking for in #248 

Can you please elaborate on why we should start at 0?

Btw, CMake has infrastructure for managing some of this by creating the appropriate symbolic links (`libcaf_mpi.so ==> libcaf_mpi.so.MAJOR ==> libcaf_mpi.so.MAJOR.MINOR) and has mechanisms for controlling compatibility (via `find_package(opencoarrays)`)...

We are using semantic versioning, which, in general, is a necessary but *not* sufficient condition for ABI compatibility---I agree with you there.

Perhaps I am missing other cases for when ABI compatibility can break despite not bumping the semver major version, but the only other one I can think of is due to the version of the compiler being used. The ABI  compatibility is dependent on the version of GCC the library was built with, since it interfaces with GCC internals and the gfortran runtime. The library itself is written completely in C, so I don't believe that other Fortran ABI issues are relevant. Therefore, ABI compatibility issues could arise if the user tries to link with OpenCoarrays using a different version of GCC than the library was built with. But this isn't changes in OpenCoarrays resulting in differences in the ABI, it's changes in the build process.

Can you envision any other cases that would break the ABI without having to bump the semver major version?

**Pull request merged**
