### PR TITLE
Fix using co_reduce(...operator=...) for F2018.

### PR DESCRIPTION
**Pull request by vehre**
In F2018 and with gcc>=12 is has to be co_reduce(...operation=...).

[links]:#
[contributing guidelines]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md
[issue]: https://github.com/sourceryinstitute/OpenCoarrays/issues
[coverage]: https://img.shields.io/codecov/c/github/sourceryinstitute/OpenCoarrays/master.svg?style=flat-square

|  coverage on master         |
|:---------------------------:|
| ![Codecov branch][coverage] |

## Summary of changes ##

Fix using co_reduce(...operator=...) for F2018.

## Rationale for changes ##

gcc >= 12 implements the F2018 change for the co_reduce( operator=...)-parameter to be named 'operation=...'. This patch fixes the different naming by using the pre-processor where operator is used. 

## Additional info and certifications ##

This pull request (PR) is a:

- [x] Bug fix
- [ ] Feature addition
- [ ] Other, Please describe:

### I certify that ###

- [x] I certify that:
  - I have reviewed and followed the [contributing guidelines]
  - I will wait at least 24 hours before self-approving the PR to give another
    OpenCoarrays developer a chance to review my proposed code
  - I have not introduced errant white space (no trailing white space or white space errors may
    be introduced)
  - I have added an explanation of what these changes do and why they should be included
  - I have checked to ensure there aren't other open [Pull Requests] for the same change
  - I have you written new tests for these changes
  - I have successfully tested these changes locally
  - I have commented any non-trivial, non-obvious code changes
  - The commits are logically atomic, self consistent and coherent
  - The [commit messages] follow [best practices]
  - Test coverage is maintained or increased after this is merged

## Code coverage data

coverage on master

[links]: #
[best practices]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[commit messages]: https://thoughtbot.com/blog/5-useful-tips-for-a-better-commit-message
[Pull Requests]: https://github.com/sourceryinstitue/OpenCoarrays/pulls

### CODE REVIEW

**Comment by everythingfunctional** [comment]
Just a quick background question. Is OpenCoarrays intended to work with any compilers other than gfortran? If so, I'd suggest reversing the preprocessor condition so that only gfortran versions less than 12 use the old argument name. Other than that this is a straightforward addition and it looks good to me.

**Comment by rouson** [comment]
@everythingfunctional other compiler development teams are considering using OpenCoarrays, but if [Caffeine] progresses quickly enough, then I think it's more likely that other compilers will adopt Caffeine -- at least that's the hope.

@vehre if you agree with the above comment by @everythingfunctional , please make the suggested edit, push again, and I'll merge or possibly you can merge now that the main branch is no longer protected.  If so, feel free to do so.

**Comment by vehre** [comment]
I have reversed the preprocessor directives. At least I hope this is what @everythingfunctional meant?!

**Comment by everythingfunctional** [comment]
I think that works. Do you know how that evaluates if `__GNUC__` isn't defined (e.g. you're using a different compiler)? If it evaluates to false, then yeah, that's perfect, but I'm not sure. Maybe it should be `#if defined(__GNUC__) && __GNUC__ < 12`?

**Comment by vehre** [comment]
> I think that works. Do you know how that evaluates if `__GNUC__` isn't defined (e.g. you're using a different compiler)? If it evaluates to false, then yeah, that's perfect, but I'm not sure. Maybe it should be `#if defined(__GNUC__) && __GNUC__ < 12`?

Updated that, ok for merge now?

**Review by rouson — APPROVED** [review]
LGTM

**Pull request merged**
