### PR TITLE
Merge post-1.6.0-release master into caffeinated-opencoarrays

### PR DESCRIPTION
**Pull request by rouson**

### CODE REVIEW

**Comment by zbeekman** [comment]
@rouson I can work to resolve these conflicts, if this is ready to merge

**Comment by rouson** [comment]
@zbeekman yes, please do.

**Comment by zbeekman** [comment]
I'm going to wait until I've merged a few outstanding PRs, namely #195 and #194

**Comment by zbeekman** [comment]
@rouson Can you please test this to make sure I didn't mess anything up here? Specifically that the caf script gets written correctly and incorporates your fixes to #193 correctly?

**Comment by zbeekman** [comment]
In particular the files to scrutinize are `caf-foot`, `src/mpi/CMakeLists.txt` and `prerequisites/install-functions/find_or_install.sh`

**Pull request merged**
