### PR TITLE
Addresses issue 235

### PR DESCRIPTION
**Pull request by afanfa**
Address #235

### CODE REVIEW

**Comment by rouson** [comment]
@afanfa and @zbeekman Any ideas why this test is failing?  Based on the Travis-CI transcript it looks like the build stalled at some point.

**Comment by zbeekman** [comment]
test time out. I resubmitted it. Even if it doesn't pass, it gets tested twice since its an internal PR, so I wouldn't have problems merging, since it passed [here](https://travis-ci.org/sourceryinstitute/opencoarrays/builds/172032448) already.

**Comment by zbeekman** [comment]
LGTM

**Comment by rouson** [comment]
All tests pass so I'm merging and closing.

**Pull request merged**
