### PR TITLE
Add ofp

### PR DESCRIPTION
**Pull request by zbeekman**
# Superseded by #147 

Please don't merge yet. I am going to squash down/fixup some of these commits

### CODE REVIEW

**Comment by zbeekman** [comment]
@rasmussn Can you please click [here](https://cla-assistant.io/sourceryinstitute/opencoarrays?pullRequest=137) and agree to the CLA?

**Comment by zbeekman** [comment]
please don't merge this yet, I'm thinking of cleaning up some of those commits.

**Comment by rouson** [comment]
@zbeekman Is it ok to push more commits to this branch or does that need to wait until your intended work on the existing commits happens.  Craig and I are likely to have new commits to push soon.

**Comment by zbeekman** [comment]
keep pushing here if you like, thats fine with me, we'll hold off on merging until you guys are at a good resting point

**Comment by rouson** [comment]
Will do.

**Comment by zbeekman** [comment]
@rouson if you speak with @rasmussn can you please remind him to sign the CLA by clicking the link here? https://cla-assistant.io/sourceryinstitute/opencoarrays?pullRequest=137

**Comment by zbeekman** [comment]
Rejected due to  history cleanup concerns and superseded by #147

**Pull request closed without merging**
