### PR TITLE
Doc cleanup

### PR DESCRIPTION
**Pull request by zbeekman**
Making this PR against master... These changes should probably be applied to the 1.x.x branch too.

### CODE REVIEW

**Comment by rouson** [comment]
Could you submit these as pull requests?

Damian 
510-600-2992 (mobile)

**Comment by zbeekman** [comment]
Hi Damian,
I'm a bit confused, this is a pull request! Do you want me to squash the commits into 1? (I didn't do this because it obfuscates some history when files are renamed and edited.

**Comment by rouson** [comment]
No.  Apprentice I'm the ones that's confused. I thought it was just an issue report and I could t see where to clock to see the changes.  I'll look at it again a bit later when I'm more awake and hopefully thinking more clearly. 

D

**Comment by sourceryinstitute** [comment]
> On Dec 3, 2015, at 6:29 AM, Damian Rouson <notifications@github.com> wrote:
> 
> No. Apprentice I'm the ones that's confused.

“Apprentice” should have been “Apparently.”  Autocorrect is my nemesis.

D

**Comment by zbeekman** [comment]
haha, me too. At any rate, I'd be happy to be your apprentice any day.

**Comment by zbeekman** [comment]
@rouson I know you're super busy this week until Thursday night, but I just wanted to make sure that this hasn't gotten lost. If you can't look at it until Friday that's fine.

**Comment by zbeekman** [comment]
These are minor changes, and just effect minor edits to the README.md etc.

Got the verbal OK from @rouson on the phone just now, so I'm going to merge this. If there are objections we can always undo the changes in a new commit.

**Pull request merged**
