### PR TITLE
Add random_init() and testcase.

### PR DESCRIPTION
**Pull request by vehre**
[links]:#
[contributing guidelines]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md
[issue]: https://github.com/sourceryinstitute/OpenCoarrays/issues
[coverage]: https://img.shields.io/codecov/c/github/sourceryinstitute/OpenCoarrays/master.svg?style=flat-square

|  coverage on master         |
|:---------------------------:|
| ![Codecov branch][coverage] |

## Summary of changes ##

Add handling for `random_init()` for mpi_caf.

## Rationale for changes ##

The api in gfortran has changed and this patch applies this change for OpenCoarrays by implementing random_init and testcases.

## Additional info and certifications ##

This pull request (PR) is a:

- [ ] Bug fix
- [x] Feature addition
- [ ] Other, Please describe:

### I certify that ###

- [x] I certify that:
  - I have reviewed and followed the [contributing guidelines]
  - I will wait at least 24 hours before self-approving the PR to give another
    OpenCoarrays developer a chance to review my proposed code
  - I have not introduced errant white space (no trailing white space or white space errors may
    be introduced)
  - I have added an explanation of what these changes do and why they should be included
  - I have checked to ensure there aren't other open [Pull Requests] for the same change
  - I have you written new tests for these changes
  - I have successfully tested these changes locally
  - I have commented any non-trivial, non-obvious code changes
  - The commits are logically atomic, self consistent and coherent
  - The [commit messages] follow [best practices]
  - Test coverage is maintained or increased after this is merged

## Code coverage data

coverage on master

[links]: #
[best practices]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[commit messages]: https://thoughtbot.com/blog/5-useful-tips-for-a-better-commit-message
[Pull Requests]: https://github.com/sourceryinstitue/OpenCoarrays/pulls

### CODE REVIEW

**Review by rouson — APPROVED** [review]
LGTM

**Comment by rouson** [comment]
@vehre the GitHub interface on this PR contained a notification that the branch was not up-to-date with `main` so I clicked the button to update the branch.  This relaunched the CI tests, resulting in a [failure](https://github.com/sourceryinstitute/OpenCoarrays/pull/734/checks?check_run_id=2469293616) on building the new unit test.  Please take a look at this and fix it if possible.

**Comment by vehre** [comment]
Sorry, made the beginner's mistake to not add the testcase's source code to the commit. This is fixed now. 
Because the gfortran side is not yet on master (I am working on it!), the testcase is not run. For this a recent gfortran 12 is needed.

**Comment by rouson** [comment]
@vehre for some reason, the CI check doesn't show that you signed the Contributor License Agreement (CLA) even though surely you did years ago.  Could you please try signing it again so that this can be merged?  Is it ready to be merged?

**Comment by vehre** [comment]
Er, well, how do I sign this license again? I see no link that I can click on.

gcc-11 now has the patch for random_init, so this is ready to be merged here in OpenCoarrays, too.

**Pull request closed without merging**
