### PR TITLE
Fix issue 123 build ftp fails on linux

### PR DESCRIPTION
**Pull request by rouson**

### CODE REVIEW

**Comment by zbeekman** [comment]
I'm going to try to test this on my work machine... which is sooooo sad... Everything is old crusty and outdated. We're giving our in house lustre-fs the heave-ho in the next 6 months--1yr I beleive at which point we'll have a saner setup.... but it's a good worst case scenario platform to use for testing... right now I think I can get almost everything besides gcc to build.

**Comment by zbeekman** [comment]
didn't have a chance to test on my work machine today. Going to ssh in in the AM if all goes to plan

**Comment by rouson** [comment]
I'm closing this pull request and will submit a new one with a few more fixes later today. I am now able to build in a nearly bare Linux virtual machine after installing only the packages mentioned in my comment on issue #125.

Hopefully I'm doing this in the right place this time.  I'm sure there's a correlation between software defect rates and attempting to multitask while trying to get one's son ready to leave the house. ;)

**Comment by zbeekman** [comment]
If you get a chance to push changes up to your branch go ahead and do so so that I can take them for a spin on the sad RHEL 5 workstation.

**Pull request closed without merging**
