### PR TITLE
issue 488

### PR DESCRIPTION
**Pull request by neok-m4700**
[links]:#
[contributing guidelines]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md
[issue]: https://github.com/sourceryinstitute/OpenCoarrays/issues
[PR response img]: https://img.shields.io/issuestats/p/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square
[coverage]: https://img.shields.io/codecov/c/github/sourceryinstitute/OpenCoarrays/master.svg?style=flat-square

|  Avg response time                |  coverage on master         |
|:---------------------------------:|:---------------------------:|
| ![Issue Stats][PR response img]   | ![Codecov branch][coverage] |

## Summary of changes ##

see #488 

please comment on how I can smoothly integrate the mwe described in the issue to the testsuite ?

## Additional info and certifications ##

This pull request (PR) is a:

- [x] Bug fix
- [ ] Feature addition
- [ ] Other, Please describe:

### I certify that ###

- [x] I reviewed and followed the [contributing guidelines], including
      - Increasing test coverage for all feature-addition PRs
      - Increasing test coverage for all bug-fix PRs for which there
        does not already exist a related test that failed before the PR
      - At least maintaining test coverage for all other PRs
      - Ensuring that all tests pass when run locally 
      - Naming PR  to indicate work in progress (WIP) and to attach the PR
        to the appropriate bug report or feature request [issue]
      - White space (no trailing white space or white space errors may
        be introduced)
      - Commenting code where it is non-obvious and non-trivial
      - Logically atomic, self consistent and coherent commits
      - Commit message content
      - Waiting 24 hours before self-approving the PR to give another
        OpenCoarrays developer a chance to review my proposed code

### CODE REVIEW

**Comment by zbeekman** [comment]
@neok-m4700 

Looks good to me!

In the future, if you like, you can write in your commit message something like:

`Fixes #488`

That will ensure that the issue is closed when it hits master.



> please comment on how I can smoothly integrate the mwe described in the issue to the testsuite ?

Why don't I add them myself and hopefully that will teach you by example.

Currently, [we search for the text matching `Test passed.`](https://github.com/sourceryinstitute/OpenCoarrays/blob/01e5ff073752cbad0949adb4ffb2176f6d5ad844/CMakeLists.txt#L631) to indicate that a test was successful, since Fortran provides no guarantees on exit/return values etc.

**Comment by zbeekman** [comment]
@neok-m4700 Just curious did you check the "allow edits from maintainers box" on the right? I'm trying to figure out the best way to add your MWEs to PRs #494 and #495.

Here is a picture of what it looks like:

image

Instructions here: https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

I've never tried this before, and if you don't want to give us access, that's fine too.

**Comment by afanfa** [comment]
LGTM

**Comment by neok-m4700** [comment]
@zbeekman 
> Why don't I add them myself and hopefully that will teach you by example.

Perfect, I will try to mimic the integration for the next PR.

> Just curious did you check the "allow edits from maintainers box" on the right?
Yep, ticked for the 2 issues !

**Comment by afanfa** [comment]
Useful for solving #422

**Pull request merged**
