### PR TITLE
Add script to change git settings and use hooks

### PR DESCRIPTION
**Pull request by zbeekman**
- pre-commit hook to check for white-space errors
 - commit-msg hook to ensure commit messages are properly formatted
   - Commit messages should start with a capitalized imperative verb "do, fix, enable" and a brief summary, less than 50 characters long of what the commit is about
   - If multiple lines, the second line should be left blank.
   - subsequent lines should not be more than 72 characters long
 - setup line endings and white space

For more info on writing good commit messages please see:
 1. https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message
 2. http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
 3. https://www.reviewboard.org/docs/codebase/dev/git/clean-commits/

The 50 character limit may seem arbitrary, but it is important for how Github.com shows commit messages, and for how `git log --oneline` and similar display the message contents.

Once @rouson and @afanfa have had a chance to look this over and voice any concerns or make requests for changes, I will merge that. After that, you can configure your repository (or the repository AND global git settings) by running:

`developer-scripts/setup-git.sh`

or 

`developer-scripts/setup-git.sh --global`

to get all the settings properly configured.

### CODE REVIEW

**Comment by zbeekman** [comment]
I'm wondering if my forced push confused the CLA bot... after you guys get a chance to look at this, I can merge by hand

**Comment by rouson** [comment]
I think these tips are very helpful and I wish I had read them sooner. This slipped off my radar. I hope to read the links in detail tonight or tomorrow.  The first thing I see at a quick glance is a recommendation to edit .vimrc. If like to know if the edit will impact my use of vi all the time or just when writing commit messages.

**Comment by zbeekman** [comment]
I think that the edits to .vimrc will globally effect vi. However, I *think* the changes will apply everywhere, but I also *think* the only effect is to strip trailing white space. I can't think of a context in which this would be undesirable. 

(Full disclosure: I use Emacs, and am going from memory of what I recall the summary of .vimrc changes to be, since I'm currently on my phone, away from my computer.)

But never fear, even if you don't edit .vimrc, my hooks will yell at you (once you've installed and configured them) if you add trailing white space etc.

**Comment by zbeekman** [comment]
I had to temporarily disable the CLA service to allow this to be merged. I'm guessing that the forced push confused it...

**Comment by zbeekman** [comment]
I'm hesitant to merge this right before I go away, but I think I will. If you run `developer-scripts/setup-git.sh` or `developer-scripts/setup-git.sh --global` and run into problems, you can always override the git-hooks with the appropriate flags, or go into the `.git` directory and remove `.git/hooks/____`. To override the `pre-commit` and `commit-msg` hooks you can also pass the `--no-verify` flag to `git commit`.

Merry Christmas, talk to you in a week!

:christmas_tree: :gift: :santa:

**Pull request merged**
