### PR TITLE
Bump version number to 1.2.3

### PR DESCRIPTION
**Pull request by rouson**

### CODE REVIEW

**Comment by zbeekman** [comment]
:+1:

**Comment by rouson** [comment]
I tried doing a fresh clone and then entering the commands GitHub lists on this page.  The "git merge devel" step returns the following:

merge: devel - not something we can merge

Did you mean this?
	origin/devel

I guest at this point, I'll bail before I do any more damage.  Git has to be the most frustrating tool I've used in many years.  I'm not arguing against its use -- just hoping that someone someday finds a way to make it more straightforward.  I'd love to be able to merge by simply dragging nodes together on the Network graph.

**Comment by zbeekman** [comment]
Another lesson here is not to review code on my phone waiting to take off for vacation at 6AM. I should have noticed that you were bumping the version number in `devel` which is one of the few cases, where we want to apply changes to `master` but *not* `devel` I'm going to revert this now.

**Comment by szaghi** [comment]
@zbeekman I have some difficult to follow your workflow, maybe it could be helpful to have *git guidelines*. I am not going to contribute to opencoarrays (because I am not able to do), but I am trying to study your work for learning... you are too much "upstream" from me :-(

**Comment by zbeekman** [comment]
@szaghi I've been trying to cleanup some mistakes etc. and we are also planning on adding a document that clarifies and explains the development workflow.

The idea of our `devel` branch is to host changes for the next **major** release. Small build system incremental improvements and bug fixes generally should be applied to both `master`---which should be kept in a very "deployable" and stable state---as well as `devel`. (`devel` is like our GCC `trunk` 6.0.0) One obvious example (although there may be more subtle ones) of when work should **_only_** be applied to `master` is when bumping the minor and patch version numbers. `devel` stays at version 2.0.0 until it is released, at which point it gets bumped to 2.1.0 and merged *into* master. Otherwise small changes are applied to master and devel, and major changes are applied to only devel until devel is in a state that is ready to release as the next major release of opencoarrays.

I will try to get a document added to the repo to explain the workflow, but have many other things to do first.

**Comment by zbeekman** [comment]
also when a bad merge takes place it is really tricky to figure out how to undo it.

**Comment by szaghi** [comment]
@zbeekman thank you very much, it is always a pleasure to read you!

**Pull request merged**
