### PR TITLE
Fix "brew install gcc" failures on Travis macOS

### PR DESCRIPTION
**Pull request by zbeekman**
(I hope)

[links]:#
[contributing guidelines]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md
[issue]: https://github.com/sourceryinstitute/OpenCoarrays/issues
[PR response img]: https://img.shields.io/issuestats/p/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square
[coverage]: https://img.shields.io/codecov/c/github/sourceryinstitute/OpenCoarrays/master.svg?style=flat-square

|  Avg response time                |  coverage on master         |
|:---------------------------------:|:---------------------------:|
| ![Issue Stats][PR response img]   | ![Codecov branch][coverage] |

## Summary of changes ##
Travis-CI updated their environment and as a result brew install gcc broke

## Rationale for changes ##

So the CI system works again

## Additional info and certifications ##

This pull request (PR) is a:

- [ ] Bug fix
- [ ] Feature addition
- [X] Other, Please describe: Cleanup Travis-CI.org's mess when they changed the environment 😡 

### I certify that ###

- [X] I reviewed and followed the [contributing guidelines], including
      - Increasing test coverage for all feature-addition PRs
      - Increasing test coverage for all bug-fix PRs for which there
        does not already exist a related test that failed before the PR
      - At least maintaining test coverage for all other PRs
      - Ensuring that all tests pass when run locally 
      - Naming PR  to indicate work in progress (WIP) and to attach the PR
        to the appropriate bug report or feature request [issue]
      - White space (no trailing white space or white space errors may
        be introduced)
      - Commenting code where it is non-obvious and non-trivial
      - Logically atomic, self consistent and coherent commits
      - Commit message content
      - Waiting 24 hours before self-approving the PR to give another
        OpenCoarrays developer a chance to review my proposed code

### CODE REVIEW

**Comment by zbeekman** [comment]
There is a serious problem with macOS builds on travis. We aren't getting any output from the build command at all. I suspect this is a Travis-CI bug since they just updated their environment around the same time period these problems started showing up.

**Comment by rouson** [comment]
@zbeekman Thanks for investigating this.  It would be fine to turnoff the macOS builds on travis for now so we don't get false negatives.

**Comment by zbeekman** [comment]
yes, may need to do that. What a PITA

**Comment by zbeekman** [comment]
Wooohooo! So it looks like you can't embed `set -o errexit` in literal runs of bash script embedded in the `.travis.yml` yaml. This is a strong case for a refactor of `.travis.yml`. (i.e. #101) After looking at the file again, it should be pretty easy to accomplish this. The idea is to put the long lines of shell script into an actual shell script. How novel!

LGTM

**Comment by zbeekman** [comment]
Assuming these tests pass, I'm going to merge this ahead of @vehre's PR, while I wait to hear back from him about the failing test.

LGTM

**Pull request merged**
