### PR TITLE
Add install.sh/build.sh option --disable-bootstrap

### PR DESCRIPTION
**Pull request by rouson**
[links]:#
[contributing guidelines]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md
[issue]: https://github.com/sourceryinstitute/OpenCoarrays/issues
[PR response img]: https://img.shields.io/issuestats/p/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square
[coverage]: https://img.shields.io/codecov/c/github/sourceryinstitute/OpenCoarrays/master.svg?style=flat-square

|  Avg response time                |  coverage on master         |
|:---------------------------------:|:---------------------------:|
| ![Issue Stats][PR response img]   | ![Codecov branch][coverage] |

## Summary of changes ##
The `install.sh` and `build.sh` now recognize the `-z` or equivalently `--disable-bootstrap` options and add or omit the corresponding arguments during `make` of GCC.

## Rationale for changes ##
When building with a recent GCC, this can speed up the build process.

## Additional info and certifications ##

This pull request (PR) is a:

- [ ] Bug fix
- [X] Feature addition
- [ ] Other, Please describe:

### I certify that ###

- [X] I have reviewed the [contributing guidelines] and followed the
      policies on:
      - Pull request (PR) naming to indicate work in progress (WIP),
        and to attach the PR to the appropriate bug report, or feature
        request [issue]
      - White space (no trailing white space or white space errors may
        be introduced)
      - Commenting code where it is non-obvious and non-trivial
      - Running tests locally, to ensure all of them pass
      - Maintaining or increasing test coverage
      - Logically atomic, self consistent and coherent commits
      - Commit message content
      - Waiting 24 hours before self-approving the pull request to
        give another OpenCoarrays developer a chance to review my
        proposed code

### CODE REVIEW

**Comment by zbeekman** [comment]
LGTM

**Comment by zbeekman** [comment]
still
:100:

**Comment by rouson** [comment]
@zbeekman what does the red "100" mean?

**Comment by zbeekman** [comment]
> what does the red "100" mean?

It's like when you were in grade school and your teacher used red pen for everything (the merits of this practice are beyond the scope of this comment) but an underlined 100 usually meant a perfect score on the test/assignment/homework/paper/etc

**Pull request merged**
