### PR TITLE
Add interfaces changes needed for gcc-trunk and testcases.

### PR DESCRIPTION
**Pull request by vehre**
With today's commit to gcc-trunk the interface for asynchronously allocatable components in derived typed coarrays has been made availabe in gfortran. This pull request adds the necessary changes to allow compilation and running tests ok for opencoarrays again.

### CODE REVIEW

**Comment by zbeekman** [comment]
@vehre is it possible to add #ifdef guards to ensure backwards compatibility? Right now the CI tests are failing due to:

```
/home/travis/build/sourceryinstitute/opencoarrays/src/mpi/mpi_caf.c: In function ‘_gfortran_caf_deregister’:
/home/travis/build/sourceryinstitute/opencoarrays/src/mpi/mpi_caf.c:764:13: error: ‘type’ undeclared (first use in this function)
     *token, type);
             ^~~~
/home/travis/build/sourceryinstitute/opencoarrays/src/mpi/mpi_caf.c:764:13: note: each undeclared identifier is reported only once for each function it appears in
```

see, e.g., https://travis-ci.org/sourceryinstitute/opencoarrays/jobs/180093612

**Comment by vehre** [comment]
Whuups, that is a left over debugging output, which should not be there. I have pushed a new version, now closing this pull request and re-opening with updated deregister.

**Comment by rouson** [comment]
Should this pull request be open or closed?  It shows as closed, but @vehre commented 3 days ago indicates that it's being re-opened.

**Comment by vehre** [comment]
Closed! Superseeded by #261

**Pull request closed without merging**
