### PR TITLE
Enable install.sh to build CMake on OS X by using Apple LLVM

### PR DESCRIPTION
**Pull request by rouson**
Use the gcc and g++ that is installed in /usr/bin by XCode with its Command-Line Tools.

### CODE REVIEW

**Comment by zbeekman** [comment]
:+1: :ship: it! :zap:

**Comment by zbeekman** [comment]
(Unless otherwise noted, comments like the one I made above indicate that I've read over the changes, and have no objections or comments on them.)

**Comment by rouson** [comment]
Thanks for the review.  I'll commit within 24 hours of submission unless Alessandro weighs in with any concerns.

**Comment by zbeekman** [comment]
Yup, sounds good.

**Pull request merged**
