### PR TITLE
Enforce MPI progress during event_wait

### PR DESCRIPTION
**Pull request by afanfa**
[links]:#
[contributing guidelines]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md
[issue]: https://github.com/sourceryinstitute/OpenCoarrays/issues
[PR response img]: https://img.shields.io/issuestats/p/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square
[coverage]: https://img.shields.io/codecov/c/github/sourceryinstitute/OpenCoarrays/master.svg?style=flat-square

|  Avg response time                |  coverage on master         |
|:---------------------------------:|:---------------------------:|
| ![Issue Stats][PR response img]   | ![Codecov branch][coverage] |

## Summary of changes ##

Summarize what you changed

## Rationale for changes ##

Why did you make these changes?

## Additional info and certifications ##

This pull request (PR) is a:

- [x] Bug fix
- [ ] Feature addition
- [ ] Other, Please describe:

### I certify that ###

- [x] I have reviewed the [contributing guidelines] and followed the
      policies on:
      - Pull request (PR) naming to indicate work in progress (WIP),
        and to attach the PR to the appropriate bug report, or feature
        request [issue]
      - White space (no trailing white space or white space errors may
        be introduced)
      - Commenting code where it is non-obvious and non-trivial
      - Running tests locally, to ensure all of them pass
      - Maintaining or increasing test coverage
      - Logically atomic, self consistent and coherent commits
      - Commit message content
      - Waiting 24 hours before self-approving the pull request to
        give another OpenCoarrays developer a chance to review my
        proposed code

### CODE REVIEW

**Comment by afanfa** [comment]
Fixes #411 . Let's discuss this before merging.

**Comment by zbeekman** [comment]
> Fixes #411 . Let's discuss this before merging.

OK, I'll hold off on approval until we discuss...

**Comment by afanfa** [comment]
@vehre The MPI_Win_flush polls the MPI engine and ensures progress (here I assume that CAF_Win_unlock points to flush). MPI_Win_sync sometimes (like in this case I guess) is implemented as a no-op operation and it does not ensure progress.
In a situation where the MPI implementation takes advantage of the interconnect capabilities, the CAF_Win_unlock is not needed. That's why I was curious about the behavior with MVAPICH.
Polling the MPI engine with CAF_Win_unlock requires time and because we don't know a priori if we really need the CAF_Win_unlock (because we don't know which MPI implementation and interconnect the user is using) I increased the timer to avoid polling the MPI engine too ofter (which may take more than the timer increase). I hope this clarifies.

**Comment by zbeekman** [comment]
> (because we don't know which MPI implementation and interconnect the user is using)

We might be able to  setup some system introspection to determine this, no? Might it be worthwhile?

**Comment by afanfa** [comment]
@zbeekman sure, it would be helpful but not exhaustive. We need to know the MPI implementation AND the network interconnect.

**Comment by zbeekman** [comment]
@afanfa hmmm I see... the network interconnect may be difficult, because if you compile on a login/head node, you may not have access to that information... so I guess the best we can do might be check which MPI lib we're using?

**Comment by afanfa** [comment]
@zbeekman , yes, I think we can speculate. For example, if we found MVAPICH installed we can assume that an Infiniband interconnect will be used and it will probably behave as we expect (hopefully).

**Comment by zbeekman** [comment]
@afanfa what is the status of this? What needs to happen to get this fix into master?

**Comment by afanfa** [comment]
@zbeekman , please go ahead and merge this little change. We'll ask Ambra to rerun her tests with the trunk version.
Thanks.

**Comment by zbeekman** [comment]
LGTM

**Comment by vehre** [comment]
Sorry, but this does not 'look good to me'. I am sorry, that I was in the impression that when I ask a rhetorical question, it is clear that I am pointing out a mistake. Obviously it is not understood that I can provide the required MPI knowledge.

So @afanfa: Answering a MPI_Win_sync() with a MPI_Win_unlock() will neither lead to progress nor to a program running on all systems. You are right that usually CAF_Win_unlock() is expanded to MPI_Win_flush(), but not always. Therefore when one wants a flush, one writes a flush.

I apologize, that did not make myself more clear. It will not happen again, even when I then seem to be impolite. I do have very limited time, so voicing anything directly now will be my policy.

**Comment by zbeekman** [comment]
Andre,

We can easily revert this merge.

I apologize if I did not understand your comment completely. We are
definitely short on man power and expertise (because our experts like you
and Alessandro have many obligations) so I do the best job I can to keep
progress moving forwards. I don't believe this code has made it into a
release yet, either.

**Comment by vehre** [comment]
No issue Zaak. My comment was more intended to Alessandro. He has the knowledge and was expected to adapt the code. Your work on progress of opencoarrays is very much appreciated.

**Comment by vehre** [comment]
No need to revert. The pull request #426 is on top of Alessandro's.

**Pull request merged**
