### PR TITLE
Issue 340 permission fix

### PR DESCRIPTION
**Pull request by zbeekman**
| Avg response time                 | coverage on master         |
| --------------------------------- | ---------------------------|
| ![Issue Stats][PR response img]   | ![Codecov branch][coverage]|

This pull request (PR) is a:
 - [x] Bug fix
 - [ ] Feature addition
 - [ ] Other, Please describe:

I certify that:

 - [x] I have reviewed the [contributing guidelines]
 - [x] If this PR is a work in progress I have added `WIP:` to the
       beginning of the PR title
 - [x] If this PR is problematic for any reason, I have added
       `DO NOT MERGE:` to the beginning of the title
 - [x] The branch name and title of this PR contains the text
       `issue-<#>` where `<#>` is replaced by the issue that this PR
       is addressing
 - [x] I have deleted trailing white space on any lines that this PR
       touches
 - [x] I have used spaces for indentation on any lines that this PR
       touches
 - [x] I have included some comments to explain non-obvious code
       changes
 - [x] I have run the tests localy (`ctest`) and all tests pass
 - [x] Each commit is a logically atomic, self-consistent, cohesive
       set of changes
 - [x] The [commit message] should follow [these guidelines]:
     - [x] First line is directive phrase, starting with a capitalized
           imperative verb, and is no longer than 50 characters
           summarizing your commit
     - [x] Next line, if necessary is blank
     - [x] Following lines are all wrapped at 72 characters and can
           include additional paragraphs, bulleted lists, etc.
     - [x] Use [Github keywords] where appropriate, to indicate the
           commit resolves an open issue.
 - [x] I have signed  [Contributor License Agreement (CLA)] by
       clicking the "details" link to the right of the `licence/cla`
       check and following the directions on the CLA assistant webpage
 - [x] I have ensured that the test coverage hasn't gone down and added new [unit tests] to cover an new code added to the library

## Summary of changes ##

Made installed scripts 555 permissions

## Rationale for changes ##

Installed software should not be group or world writeable, since this is a huge security vulnerability, obviously.

## For contributors and SI team members with code review priviledges ##

 - [X] I certify that I will wait 24 hours before self-approving via
       [pullapprove comment] or [Github code review] so that someone
       else has the chance to review my proposed changes

[links]:#
[contributing guidelines]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md
[commit message]: https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message
[these guidelines]: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[Contributor License Agreement (CLA)]: https://cla-assistant.io/sourceryinstitute/OpenCoarrays
[pullapprove comment]: https://pullapprove.com/sourceryinstitute/OpenCoarrays/settings/
[Github code review]: https://help.github.com/articles/about-pull-request-reviews/
[Github keywords]: https://help.github.com/articles/closing-issues-via-commit-messages/
[unit tests]: https://github.com/sourceryinstitute/OpenCoarrays/tree/master/src/tests/unit
[PR response img]: https://img.shields.io/issuestats/p/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square
[coverage]: https://img.shields.io/codecov/c/github/sourceryinstitute/OpenCoarrays/master.svg?style=flat-square

### CODE REVIEW

**Comment by rouson** [comment]
Let's move Summary of Changes and Rationale for Changes to the top of this file and the template(s).

**Comment by zbeekman** [comment]
@rouson if you have a chance to look at this and give it a "LGTM" or provide comment that would be great. Feel free to merge too, I'm done. If this happens in the next 5 min I'll try to upload release assets before going to the gym. Otherwise I'll do it when I return.

**Comment by rouson** [comment]
LGTM

**Comment by rouson** [comment]
@zbeekman, I'll let you merge in case you want to wait for the tests to complete.

**Comment by zbeekman** [comment]
They were about to finish but then I realized the release signing and
deploy script would error on the tag build. My changes shouldn't impact
non-tag builds and I probably should have added `[ci-skip]`. Feel free to
merge if the second to last commit has a green check. This will help clear
any ci backlog whil I'm at the gym.

**Comment by zbeekman** [comment]
LGTM

**Pull request merged**
