### PR TITLE
Expand test matrix to include install.sh script and `build`

### PR DESCRIPTION
**Pull request by zbeekman**
Missing from this PR, i.e., still under development:

 - Clever managing which dependencies are pre-loaded through more expedient Travis-CI logic, when build scripts have not been touched, but building as much as we can when modified in the commit range being tested by Travis-CI
 - Testing car wrapper scripts after OpenCoarrays has been installed (This isn't done in any tests yet)

Additionally, `.travis.yml` is getting unwieldy and could benefit from being broken up into one or more shell scripts ( #101 )

### CODE REVIEW

**Comment by zbeekman** [comment]
Note, that the indiscriminate "build everything you can" approach causes the tests to run for close to 30 minutes instead of under two. That's why it will be important to examine the commit range to see if `install.sh` or anything in `install_prerequisites/*` has changed and avoid building CMake and MPICH in those cases.

**Comment by zbeekman** [comment]
:zap:

**Comment by rouson** [comment]
Your message has the "| pullapprove | approve |" buttons but the code-review/pullaprove still shows as pending.  ????

**Comment by zbeekman** [comment]
@rouson, I don't know, but maybe? I got in touch with pull approve support to see what they have to say.

**Comment by zbeekman** [comment]
:+1: Will a second try work?

**Pull request merged**
