### PR TITLE
Pull in fix for broken builds due to Homebrew GCC 6.1 upgrade

### PR DESCRIPTION
**Pull request by zbeekman**
Should be a simple merge

### CODE REVIEW

**Comment by zbeekman** [comment]
@rouson 

1. It seems that the OS X build has errored, due to stratego-xt/sdf/aterm/OFP related causes: https://travis-ci.org/sourceryinstitute/opencoarrays/jobs/136145593#L5273-L5278 Is this because of an interaction with the need for `sudo` and `--yes-to-all`? 
1. The build script throws an error and aborts on Linux because "OFP source translation is currently only supported on OS X" https://travis-ci.org/sourceryinstitute/opencoarrays/jobs/136145596#L4676-L4678 Can we have this emit a warning instead, and just build OpenCoarrays without support for non-GCC compilers?

**Comment by rouson** [comment]
@zbeekman 

We're just taking a break from from the standards committee meeting.   I'll try to reach you via screenhero or mobile phone to discuss this.

**Comment by zbeekman** [comment]
LGTM

**Comment by szaghi** [comment]
@rouson Very Off Topic: if you are attending a committee meeting of Fortran please convey all the google-discussions instances about more *generics, flexible containers, oop, etc...*. You are our hero!

**Comment by rouson** [comment]
@szaghi  Thanks for your message and the vote of confidence!  In August 2015, the committee approved a resolution indicating that the soonest new features will be considered is 2017.  Certainly, there is interest in generics, flexible containers, and additional OOP features.  Proposing new features is really challenging because so many compiler providers aren't yet Fortran 2008-compliant and a few aren't even yet 2003-compliant.  Please consider attending a meeting if that's an option for you.  The next meeting will be in October in Las Vegas. Sometime before the February 2017 meeting, I'm hoping to put together a survey on [SurveryMonkey](www.surveymonkey.com) to solicit user input that would inform the committee on user demand for new features.

**Comment by szaghi** [comment]
@rouson Dear Damian, I am not up to attend at such meetings (I have not the competence), but I will like to contribute with my *user-inputs* if they will be meaningful. Thank you very much to exist :smile:

**Pull request merged**
