### PR TITLE
Pull in `stop` bug fix and other recent changes on `master`

### PR DESCRIPTION
**Pull request by zbeekman**
`devel` has fallen a little bit behind `master`...

Let's get them back in sync

 - #160 and #162 
 - #156 
 - #159

### CODE REVIEW

**Comment by zbeekman** [comment]
This will require some manual command line merging. I also need to be extra careful since I'm a bit rusty on the current state of `devel`

**Comment by zbeekman** [comment]
LGTM

**Comment by rouson** [comment]
@zbeekman thanks for working on this.  My guess is devel will be dormant for a bit until we are close to the [2.0.0](https://github.com/sourceryinstitute/opencoarrays/milestones/2.x%20release) release, for which I've set a tentative target date of May 30.  The most important requirements for 2.0.0 in my view is the integration of OFP as marked by issue #154 and #119.  A close second would be #118, but that has a slightly lower priority because (1) a much broader set of similar functionality will be available when we enable CAFe after the OFP integration, (2) @afanfa won't generally be available for OpenCoarrays work after starting his postdoc (except for working on failed-image support, which is the subject of the postdoc), and (3) I'm pursuing funding related to #118 and it makes sense to await the funding decision before proceeding.  We'll see how many of the other milestone issues we can resolve but even just finishing the OFP integration is a big enough deal for the release -- assuming the [1.4.0](https://github.com/sourceryinstitute/opencoarrays/milestones/1.4.0%20release) release milestone issues have been closed before we approach the 2.0.0.  I've set a tentative date for 1.4.0 release of April 30.

**Comment by zbeekman** [comment]
Sounds great!

**Pull request merged**
