### PR TITLE
Merge opencoarrays-teams into master

### PR DESCRIPTION
**Pull request by rouson**
[links]:#
[contributing guidelines]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md
[issue]: https://github.com/sourceryinstitute/OpenCoarrays/issues
[PR response img]: https://img.shields.io/issuestats/p/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square
[coverage]: https://img.shields.io/codecov/c/github/sourceryinstitute/OpenCoarrays/master.svg?style=flat-square

|  Avg response time                |  coverage on master         |
|:---------------------------------:|:---------------------------:|
| ![Issue Stats][PR response img]   | ![Codecov branch][coverage] |

## Summary of changes ##

Work in Progress: This pull request adds support for most Fortran 2018 teams features.  Most of the code was originally developed by @afanfa with some more recent contributions from @scrasmussen and me.  We would especially appreciate feedback from @afanfa and @vehre regarding the new `team_number()` intrinsic function, which I added.  The latest work on the compiler side is on the [teams branch] of the Sourcery Institute GCC fork and has been submitted as a patch to the gfortran developers for review.  We have a few remaining items to handle before merging this pull request:

- [x] Add compiler support for `team_number()` and then remove the dependence on the opencoarrays module via `use opencoarrays, only : team_number`.
- [x]  Resolve why the [team_number test] builds cleanly and executes without error when run outside of `ctest` but fails when run by ctest.
- [x] Resolve why cmake can't find the `mpi.mod` file when it encounters the `use mpi, only : mpi_comm` statement in the [get_communicator test], which causes the test to fail.

## Rationale for changes ##

This adds partial support for the only major Fortran 2018 feature that is currently unsupported in the released versions of GCC and OpenCoarrays.

## Additional info and certifications ##

This pull request (PR) is a:

- [ ] Bug fix
- [X] Feature addition
- [ ] Other, Please describe:

### I certify that ###

- [X] I reviewed and followed the [contributing guidelines], including
      - Increasing test coverage for all feature-addition PRs
      - Increasing test coverage for all bug-fix PRs for which there
        does not already exist a related test that failed before the PR
      - At least maintaining test coverage for all other PRs
      - Ensuring that all tests pass when run locally 
      - Naming PR  to indicate work in progress (WIP) and to attach the PR
        to the appropriate bug report or feature request [issue]
      - White space (no trailing white space or white space errors may
        be introduced)
      - Commenting code where it is non-obvious and non-trivial
      - Logically atomic, self consistent and coherent commits
      - Commit message content
      - Waiting 24 hours before self-approving the PR to give another
        OpenCoarrays developer a chance to review my proposed code

[teams branch]: https://github.com/sourceryinstitute/gcc/tree/teams
[team_number test]: https://github.com/sourceryinstitute/OpenCoarrays/blob/opencoarrays-teams/src/tests/unit/teams/team-number.f90
[get_communicator test]: https://github.com/sourceryinstitute/OpenCoarrays/blob/opencoarrays-teams/src/tests/unit/teams/get-communicator.f90

### CODE REVIEW

**Comment by rouson** [comment]
I took off the "WIP" preface on this issue.  The teams patch has been submitted to the appropriate GCC mailing lists for approval.  Let's merge this and release ASAP so that OpenCoarrays is ready to support the teams features that will hopefully be committed to the GCC trunk soon and released in GCC 8.

**Comment by zbeekman** [comment]
Unless anyone objects I would like to merge the issue-422... branch into this one. My rational is:

 - It contains important fixes/updates for the Travis-CI testing infra which has undergone extensive upstream changes
 - It is a fairly large and disruptive change and I want to ensure that it is compatible with the teams branch; the sooner we can test this, the sooner we can work on any issues that pop up.

@afanfa @scrasmussen @rouson let me know if you have any objections

**Comment by rouson** [comment]
@zbeekman Now that the issue-422 branch has been merged into master, would it make more sense to just merge master into opencoarrays-teams?

**Comment by zbeekman** [comment]
@rouson said:

> Now that the issue-422 branch has been merged into master, would it make more sense to just merge master into opencoarrays-teams?

Yes, I've just done that after merging the latest Travis-CI fixups (PR #480)

@rouson @afanfa @scrasmussen Is this PR ready to be merged, assuming the checks pass?

**Comment by zbeekman** [comment]
LGTM

**Pull request merged**
