### PR TITLE
Descriptor fix

### PR DESCRIPTION
**Pull request by zbeekman**
[links]:#
[contributing guidelines]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md
[issue]: https://github.com/sourceryinstitute/OpenCoarrays/issues
[PR response img]: https://img.shields.io/issuestats/p/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square
[coverage]: https://img.shields.io/codecov/c/github/sourceryinstitute/OpenCoarrays/master.svg?style=flat-square

|  Avg response time                |  coverage on master         |
|:---------------------------------:|:---------------------------:|
| ![Issue Stats][PR response img]   | ![Codecov branch][coverage] |

## Summary of changes ##

Update libcaf header for new component in array descriptor

## Rationale for changes ##

GCC 8.x added a new component to the array descriptor struct and if we don't match it, the OC tests fail

## Additional info and certifications ##

This pull request (PR) is a:

- [ ] Bug fix
- [ ] Feature addition
- [X] Other, Please describe: compatibility with GFortran udpate

### I certify that ###

- [x] I reviewed and followed the [contributing guidelines], including
      - Increasing test coverage for all feature-addition PRs
      - Increasing test coverage for all bug-fix PRs for which there
        does not already exist a related test that failed before the PR
      - At least maintaining test coverage for all other PRs
      - Ensuring that all tests pass when run locally 
      - Naming PR  to indicate work in progress (WIP) and to attach the PR
        to the appropriate bug report or feature request [issue]
      - White space (no trailing white space or white space errors may
        be introduced)
      - Commenting code where it is non-obvious and non-trivial
      - Logically atomic, self consistent and coherent commits
      - Commit message content
      - Waiting 24 hours before self-approving the PR to give another
        OpenCoarrays developer a chance to review my proposed code

### CODE REVIEW

**Comment by zbeekman** [comment]
@rouson my initial patch would cause GCC < 8 to fail/hang because the additional component of the descriptor struct is only present in 8... so I added some `#ifdef` guards to ensure it's only inserted if we're building against GFortran >= 8/trunk. I have tested this with GCC 7 but not with 8.

@rouson Could you please test this with GCC trunk/8?

**Comment by rouson** [comment]
LGTM

**Comment by zbeekman** [comment]
LGTM

**Comment by vehre** [comment]
The patch for using gcc8's extended descriptor was not complete. There is another descriptor-declaration in the .c-file, where the descriptor_dimensions are declared with GFC_MAX_DIMENSION instead of [] like in the .h file. Above commit fixes this issue now.

**Comment by zbeekman** [comment]
Great, thanks so much Andre!

LGTM

**Pull request merged**
