### PR TITLE
CMake opt flag fix

### PR DESCRIPTION
**Pull request by zbeekman**
This PR makes it so that user selected CMake build types don't add optimization flags to GFortran. This is due to a GFortran bug which @afanfa has apparently already submitted a patch for. I don't know what it's status is, however.

@afanfa, do you have a link to the issue tracker or some other means of monitoring the bug?

For more back story see #27, #28 and Homebrew/homebrew#46547 and also https://groups.google.com/forum/#!msg/opencoarrays/RZOwwYTqG80/46S9eL696dgJ

### CODE REVIEW

**Comment by afanfa** [comment]
You can track the review process here: https://groups.google.com/forum/m/#!topic/opencoarrays/IOx0RFLJEr0

**Comment by zbeekman** [comment]
Also, @rouson and @afanfa,
Do you think I should create an advanced cache variable to allow users to turn of my `-O0` override? Perhaps some people want to live dangerously and prefer faster code even if it could be incorrect? Thoughts?

**Comment by zbeekman** [comment]
Some more tweaks and changes are required as per discussion with @rouson... Will try to get to them soon.

**Comment by zbeekman** [comment]
This was rebased onto the changes being made to master to bring it closer to branch-1.x

**Comment by zbeekman** [comment]
Fixed as #71

**Pull request closed without merging**
