### PR TITLE
Update and cleanup markdown files

### PR DESCRIPTION
**Pull request by zbeekman**
Cleanup and update markdown files, also try to address #29 and add some PR and issue templates

### CODE REVIEW

**Comment by rouson** [comment]
@zbeekman everyone on the new list has been helpful and it's great to include them.  Just to avoid any confusion, has each person contributed code?  If not, it might be good to separate the list into two more more groups based on the form of contribution.  If there is ever a desire to release OpenCoarrays under a different license (which I don't necessarily anticipate), it will be necessary to obtain the permission of each contributor of code so the ewer people designated as such, the easier will be that process.

**Comment by zbeekman** [comment]
@rouson: 
> @zbeekman everyone on the new list has been helpful and it's great to include them. Just to avoid any confusion, has each person contributed code?

I believe so. Not to `master` necessarily. I came up with this list through the following methodology, cross referencing the following sources:

 1. https://github.com/sourceryinstitute/opencoarrays/graphs/contributors
 2. Combing through the git history with: `git log --all --format='%aN <%aE>' | awk '{arr[$0]++} END{for (i in arr){print arr[i], i;}}' | sort -rn | cut -d\  -f2-` which will dump all authors and their emails and sort them based on number of commits
 3. [Exporting everyone who has signed](https://cla-assistant.io) the [CLA](https://gist.github.com/0a5d60a1cbd1f6a8cfa5) 
[old-CLA.csv.txt](https://github.com/sourceryinstitute/opencoarrays/files/768790/old-CLA.csv.txt)

| User Name | Repository Owner | Repository Name | CLA Title | Gist URL | Gist Version | Signed At | Signed for Organization |
|---|---|---|---|---|---|---|---|
| zbeekman | sourceryinstitute | opencoarrays | Linux Foundation CLA | https://gist.github.com/0a5d60a1cbd1f6a8cfa5 | 4cb0a6480ba97e16753b19c2788d2b0e4737b5fa | 2015-12-14T19:38:21.632Z | FALSE |
| rouson | sourceryinstitute | opencoarrays | Linux Foundation CLA | https://gist.github.com/0a5d60a1cbd1f6a8cfa5 | 4cb0a6480ba97e16753b19c2788d2b0e4737b5fa | 2015-12-15T18:48:26.711Z | FALSE |
| afanfa | sourceryinstitute | opencoarrays | Linux Foundation CLA | https://gist.github.com/0a5d60a1cbd1f6a8cfa5 | 4cb0a6480ba97e16753b19c2788d2b0e4737b5fa | 2015-12-17T09:24:35.576Z | FALSE |
| rasmussn | sourceryinstitute | opencoarrays | Linux Foundation CLA | https://gist.github.com/0a5d60a1cbd1f6a8cfa5 | 231b09bc996eb1a6d9e421b2323645ce0dcbf851 | 2016-02-05T18:35:29.053Z | FALSE |
| scrasmussen | sourceryinstitute | opencoarrays | Linux Foundation CLA | https://gist.github.com/0a5d60a1cbd1f6a8cfa5 | 231b09bc996eb1a6d9e421b2323645ce0dcbf851 | 2016-06-10T16:28:03.231Z | FALSE |
| vehre | sourceryinstitute | opencoarrays | Linux Foundation CLA | https://gist.github.com/0a5d60a1cbd1f6a8cfa5 | 231b09bc996eb1a6d9e421b2323645ce0dcbf851 | 2016-09-22T14:45:16.497Z | FALSE |
| LaHaine | sourceryinstitute | opencoarrays | Linux Foundation CLA | https://gist.github.com/0a5d60a1cbd1f6a8cfa5 | 231b09bc996eb1a6d9e421b2323645ce0dcbf851 | 2017-01-13T13:01:07.642Z | FALSE |

 4. To update the CLA assistant I searched for all authors in the git history who had the 'Signed-off-by' line in their commit messages: `git log --all --grep "[Ss]igned-off-by"  --format='%aN <%aE> %aI' | awk '{arr[$0]++} END{for (i in arr){print arr[i], i;}}' | sort -rn | cut -d\  -f2-` and then used the import feature to import Tobias, Naveen, and Jeff
 5. I left all previous contributors listed, even if I couldn't find them using the techniques listed above, this is the case for Daniel Carrera, who was [added by Tobias 3 years ago](https://github.com/sourceryinstitute/opencoarrays/blame/a87681e09b751e041fa21e5a91b563d3dc2c4f93/AUTHORS.md#L7), but I have no idea what, if anything he has contributed.
 6. I have yet to log in to bitbucket to see if I can excavate any additional old info about authors from the old repo there, if it's still present...


> If not, it might be good to separate the list into two more more groups based on the form of contribution.

Sure, I agree, but so far these all seem to be in the git history, so all of these people have committed code or documentation to the project. (Except perhaps Daniel Carrera)

> If there is ever a desire to release OpenCoarrays under a different license (which I don't necessarily anticipate), it will be necessary to obtain the permission of each contributor of code so the fewer people designated as such, the easier will be that process.

I'm no lawyer, but I would have thought that the CLA would have a clause signing their rights away regarding how we license the code.... anyway I'm surprised at this. We should research this some more.

**Comment by zbeekman** [comment]
LGTM

**Comment by zbeekman** [comment]
This is a documentation only PR, so I'm going to merge it once the tests pass

**Comment by zbeekman** [comment]
@rouson take a look at my comment about the contributors above. We can look through the commits and see what each of the contributors added, to determine whether or not they belong in the AUTHORS.md as a contributor of code, or if their contributions weren't of the sort that ends up in shippable code, but as I noted above, everyone one listed (with the possible exception of Daniel Carrera) has authored a commit in the repo.

**Pull request merged**
