### PR TITLE
Add logic to install Xcode-CLT if needed

### LINKED ISSUE #325: Automatically handle Xcode CLT install if needed on MacOS
See, for example how the [homebrew installer](https://github.com/Homebrew/install/blob/master/install#L110) handles this.

I have written a function to test if we need to install the CLT, but am wondering at what point do we call it and do the installation. I'm guessing every single one of our dependencies probably needs the Xcode CLT on MacOS, so, I guess we put it near the beginning of `install.sh`? Here is a function to detect if CLT are missing:

```bash
install_xcodeCLT () {
    if [[ "${OSTYPE}" != [Dd][Aa][Rr][Ww][Ii][Nn]* ]]; then
        echo "false"
    else
        local xcode_dir
        xcode_dir="$(/usr/bin/xcode-select -print-path 2>/dev/null)"
        if [[ -z "${xcode_dir}" ]] || ! [[ -x "${xcode_dir}/usr/bin/make" ]] ; then
            echo "true"
        else
            echo "false"
	fi
    fi
}
```

Works safely on other systems.

Here is the clever magic that homebrew does to get CLT installed and the EULA signed: (from https://github.com/Homebrew/install/blob/master/install#L259-L285)

```ruby
if should_install_command_line_tools?
  ohai "Searching online for the Command Line Tools"
  # This temporary file prompts the 'softwareupdate' utility to list the Command Line Tools
  clt_placeholder = "/tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress"
  sudo "/usr/bin/touch", clt_placeholder
  clt_label = `softwareupdate -l | grep -B 1 -E "Command Line (Developer|Tools)" | awk -F"*" '/^ +\\*/ {print $2}' | sed 's/^ *//' | tail -n1`.chomp
  ohai "Installing #{clt_label}"
  sudo "/usr/sbin/softwareupdate", "-i", clt_label
  sudo "/bin/rm", "-f", clt_placeholder
  sudo "/usr/bin/xcode-select", "--switch", "/Library/Developer/CommandLineTools"
end

# Headless install may have failed, so fallback to original 'xcode-select' method
if should_install_command_line_tools? && STDIN.tty?
  ohai "Installing the Command Line Tools (expect a GUI popup):"
  sudo "/usr/bin/xcode-select", "--install"
  puts "Press any key when the installation has completed."
  getc
  sudo "/usr/bin/xcode-select", "--switch", "/Library/Developer/CommandLineTools"
end

abort <<-EOABORT if `/usr/bin/xcrun clang 2>&1` =~ /license/ && !$?.success?
You have not agreed to the Xcode license.
Before running the installer again please agree to the license by opening
Xcode.app or running:
    sudo xcodebuild -license
EOABORT
```

My ruby, while poor, is good enough to translate that to bash, I believe... or come up with our own version.

### PR DESCRIPTION
**Pull request by zbeekman**
On macOS, add logic to install script that will install Xcode command
 line tools. Most logic cribbed from Homebrew installer.

 Fixes #325

[links]:#
[contributing guidelines]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md
[issue]: https://github.com/sourceryinstitute/OpenCoarrays/issues
[PR response img]: https://img.shields.io/issuestats/p/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square
[coverage]: https://img.shields.io/codecov/c/github/sourceryinstitute/OpenCoarrays/master.svg?style=flat-square

|  Avg response time                |  coverage on master         |
|:---------------------------------:|:---------------------------:|
| ![Issue Stats][PR response img]   | ![Codecov branch][coverage] |

## Summary of changes ##

If on macOS and using `install.sh`, determine if Xcode command line tools (CLT) are already installed and try to install them if they are needed.

## Rationale for changes ##

Help novice/new macOS users get their dev environment setup for development, including using OpenCoarrays. Without this, a user could download OpenCoarrays on macOS and not be able to install all the required software. `install.sh` trie to cater to the lowest common denominator, and most novice user, so it tries to be as seamless and easy as possible.

## Additional info and certifications ##

This pull request (PR) is a:

- [ ] Bug fix
- [x] Feature addition
- [ ] Other, Please describe:

### I certify that ###

- [x] I have reviewed the [contributing guidelines] and followed the
      policies on:
      - Pull request (PR) naming to indicate work in progress (WIP),
        and to attach the PR to the appropriate bug report, or feature
        request [issue]
      - White space (no trailing white space or white space errors may
        be introduced)
      - Commenting code where it is non-obvious and non-trivial
      - Running tests locally, to ensure all of them pass
      - Maintaining or increasing test coverage
      - Logically atomic, self consistent and coherent commits
      - Commit message content
      - Waiting 24 hours before self-approving the pull request to
        give another OpenCoarrays developer a chance to review my
        proposed code

### CODE REVIEW

**Comment by rouson** [comment]
I will attempt to boot a fresh copy of macOS Sierra in a virtual machine to test this pull request and report the results.

**Comment by zbeekman** [comment]
> I will attempt to boot a fresh copy of macOS Sierra in a virtual machine to test this pull request and report the results.

Great! I guess I'll wait to hear your results before merging.

**Comment by zbeekman** [comment]
@rouson any luck?

**Comment by zbeekman** [comment]
LGTM

Just waiting to see if @rouson had a chance to test...

**Comment by rouson** [comment]
I have a macOS virtual machine booting using the method described in the osxdaily.com article "[How to Run MacOS Sierra in a Virtual Machine for Free, the Easy Way](http://osxdaily.com/2017/04/11/run-macos-virtual-machine-easy-parallels/)".  I will download and test the installer now.

**Comment by rouson** [comment]
LGTM

**Pull request merged**
