### PR TITLE
Update devel from master

### PR DESCRIPTION
**Pull request by zbeekman**
@rouson this may be tricky to merge... we'll see.

### CODE REVIEW

**Comment by zbeekman** [comment]
Oh boy... we've let this go quite some time... I'm going to work on merging this now...

LGTM

**Comment by zbeekman** [comment]
@rouson it seems like something from caffeinate-opencoarrays was merged into devel, and is causing the same build-failure problem...

**Comment by rouson** [comment]
Sorry about that.  We've been occupied with meetings and such but lets see if my next few commits are helpful in resolving these issues. If nothing else, it might make sense to delay fixing them for another day or so, given that I've changed a few file names and added some new files. It's probably best to do the merge once the dust has settled.

**Comment by zbeekman** [comment]
No worries, just wanted to make sure you were aware of the issue.

**Comment by zbeekman** [comment]
I must apologize for letting these branches get so out of sync. I think I should be able to resolve any conflicts in `CMakeLists.txt`, but may need help from @afanfa (and possibly @vehre) to resolve those in `src/mpi/mpi_caf.c` I'll start looking at this, and report back if I have issues.

**Comment by zbeekman** [comment]
@rouson and @afanfa I think I can merge everything, except for `src/mpi/mpi_caf.c` I may shoot @afanfa an email with the merge conflicts attached and see if he could resolve them.

**Comment by zbeekman** [comment]
Let's hold off merging this until the work with GCC 7/trunk is wrapped up. I may try to perform an incremental merge from before this work started, just so there isn't as big of a difference.

**Comment by zbeekman** [comment]
Superseded, for now, by #263

**Pull request closed without merging**
