### PR TITLE
Merge issue-422-implement-by-refs

### PR DESCRIPTION
**Pull request by rouson**
[links]:#
[contributing guidelines]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md
[issue]: https://github.com/sourceryinstitute/OpenCoarrays/issues
[PR response img]: https://img.shields.io/issuestats/p/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square
[coverage]: https://img.shields.io/codecov/c/github/sourceryinstitute/OpenCoarrays/master.svg?style=flat-square

|  Avg response time                |  coverage on master         |
|:---------------------------------:|:---------------------------:|
| ![Issue Stats][PR response img]   | ![Codecov branch][coverage] |

## Summary of changes ##

The issue-422-implement-by-refs branch removes most of the regressions in issue #422 with two minor exceptions noted in commit 7220d64e9b84989a08ef8b61d8f1aa4e9fca1df7. 

## Rationale for changes ##

Branch issue-422-implement-by-refs is far enough along that releasing its commits will benefit users greatly, including specifically the [Coarray ICAR] project, which has been used to test this branch.

## Additional info and certifications ##

@zbeekman After we merge this, let's release ASAP.  I think we should also change the installer so that it defaults to allowing or installing GCC 7 without any special arguments.

FYI, the remaining regressions exposed by a our current test suite are all have "convert" in the name:
```
The following tests FAILED:
	 14 - alloc_comp_get_convert_nums (Failed)
	 15 - alloc_comp_send_convert_nums (Failed)
	 16 - send_convert_nums (Failed)
	 17 - sendget_convert_nums (Failed)
	 19 - send_convert_char_array (Failed)
```
Does this mean we need to reopen issue #292 to track this?

This pull request (PR) is a:

- [X] Bug fix
- [ ] Feature addition
- [ ] Other, Please describe:

### I certify that ###

- [X] I reviewed and followed the [contributing guidelines], including
      - Increasing test coverage for all feature-addition PRs
      - Increasing test coverage for all bug-fix PRs for which there
        does not already exist a related test that failed before the PR
      - At least maintaining test coverage for all other PRs
      - Ensuring that all tests pass when run locally 
      - Naming PR  to indicate work in progress (WIP) and to attach the PR
        to the appropriate bug report or feature request [issue]
      - White space (no trailing white space or white space errors may
        be introduced)
      - Commenting code where it is non-obvious and non-trivial
      - Logically atomic, self consistent and coherent commits
      - Commit message content
      - Waiting 24 hours before self-approving the PR to give another
        OpenCoarrays developer a chance to review my proposed code

[Coarray ICAR]: https://github.com/gutmann/coarray_icar

### CODE REVIEW

**Comment by rouson** [comment]
Although my test of Coarray ICAR in the Sourcery Institute virtual machine passed, tests by @gutmann failed in distributed memory on NCAR's Cheyenne platform.  I'll try some distributed-memory tests on another platform before merging this.

**Comment by vehre** [comment]
Issue #422 is quite near perfect, but yet all the way. Vector indexing has not been tested yet due to compiler bug. Sendget_by_ref is not yet tested at all and probably failing at once. So far, yes, 422 is a big step forward, but not yet complete, albeit merging it can add support for many erroring codes already. I check in a few minutes whether my local copy has more fixes already.

Am 12. Januar 2018 02:36:11 MEZ schrieb Damian Rouson <notifications@github.com>:
>Although my test of Coarray ICAR in the Sourcery Institute virtual
>machine passed, tests by @gutmann failed in distributed memory on
>NCAR's Cheyenne platform.  I'll try some distributed-memory tests on
>another platform before merging this.

-- 
Andre Vehreschild * Kreuzherrenstr. 8 * 52062 Aachen
vehre@gmx.de * Tel. +49 178 3837536

**Comment by zbeekman** [comment]
@vehre Damian and I have pushed some commits to you branch. Hopefully this doesn't screw things up for you.

One problem is that now, with GCC 6.4, mpi_caf.c no longer compiles. Do you have a chance to look into this and fix it sometime soonish?

(BTW, Travis-CI change some of their infrastructure that was causing tests to appear as if they have passed when in fact they have not.

Thanks,
Zaak

**Comment by rouson** [comment]
@zbeekman  Is the problem specific to GCC 6.4?  Do we know if early 6.x versions work?  And what about 7?  I wonder if the 6.4 issue is a compiler bug that we should report.

**Comment by zbeekman** [comment]
I suspect that the GCC 6 problem is due to improper #ifdef guarding in the
library from recent changes, but I have yet to confirm.

**Comment by zbeekman** [comment]
@vehre Any idea when you'll be able to resolve the GCC 6 build failure for the library? I think it's just missing a few `#ifdefs`

**Comment by zbeekman** [comment]
Assuming tests pass, let's go ahead and merge this. I think I've sorted out the remaining Travis-CI issues and made the testing infra more robust in the face of future Travis-CI environment changes. Some additional tweaks may be necessary, but now that the big problems are fixed I'll continue work in a separate branch.

I don't think @vehre has any objections to merging this, other than the caveats we've already discussed regarding some ongoing work, and the fact that there are still bugs in the 7.x branch of GCC affecting us. If this is not the case, @vehre please chime in and let us know.

Nice work @vehre getting these fixes/enhancements paritally/mostly implemented, and fixing so many of the regressions.

Cheers!

**Pull request merged**
