### PR TITLE
Fix GCC head url

### LINKED ISSUE #606: Misdirected URL for gcc during installation
Hello,

The URL in set_or_print_url.sh in OpenCoarrays-2.3.1 for gcc is wrong.  The original code is:

      gcc_url_head="https://ftpmirror.gnu.org/gcc/gcc-${version_to_build}/gcc-${version_to_build}.tar.xz/"

and should be:

      gcc_url_head="https://ftpmirror.gnu.org/gcc/gcc-${version_to_build}/"

Thanks!

### PR DESCRIPTION
**Pull request by zbeekman**
- Fixes #606

[links]:#
[contributing guidelines]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md
[issue]: https://github.com/sourceryinstitute/OpenCoarrays/issues
[PR response img]: https://img.shields.io/issuestats/p/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square
[coverage]: https://img.shields.io/codecov/c/github/sourceryinstitute/OpenCoarrays/master.svg?style=flat-square

## Summary of changes ##

Fix GCC head URL. I think I authored this in c56e6cdfdc683f508c3124f4c07db8bbcea115ac, even though the blame shows Damian. Perhaps we were working together in person or something.

## Rationale for changes ##

Breaks installation

## Additional info and certifications ##

This pull request (PR) is a:

- [x] Bug fix
- [ ] Feature addition
- [ ] Other, Please describe:

### I certify that ###

- [x] I reviewed and followed the [contributing guidelines], including
      - Increasing test coverage for all feature-addition PRs
      - Increasing test coverage for all bug-fix PRs for which there
        does not already exist a related test that failed before the PR
      - At least maintaining test coverage for all other PRs
      - Ensuring that all tests pass when run locally 
      - Naming PR  to indicate work in progress (WIP) and to attach the PR
        to the appropriate bug report or feature request [issue]
      - White space (no trailing white space or white space errors may
        be introduced)
      - Commenting code where it is non-obvious and non-trivial
      - Logically atomic, self consistent and coherent commits
      - Commit message content
      - Waiting 24 hours before self-approving the PR to give another
        OpenCoarrays developer a chance to review my proposed code

### CODE REVIEW

**Comment by zbeekman** [comment]
@singleterry, @rouson  If one of you have a chance to test this locally (you don't need to proceed beyond the downloading of GCC tarballs) I'd very much appreciate it. Otherwise I'll test this tomorrow or over the weekend.

**Comment by zbeekman** [comment]
FYI, I have rebased this branch and force pushed. So if you grabbed it in the last ~30 minutes you may need to do a `git fetch origin` followed by `git checkout Fix-gcc-download-url` and `git reset --hard origin/master`.

**Comment by singleterry** [comment]
Hello,

Bummer.  I just got the tarball for 2.3.1.  Therefore, I assume it will be in the next version!

Thanks
Robert

*******************************************************************************
Robert C. Singleterry Jr., Ph.D.
Research Engineer and NASA Administrator’s Fellow (Cohort 6: 2002-2004)
Durability, Damage Tolerance, & Reliability Branch
Langley Research Center, National Aeronautics and Space Administration
Building 1205, Room 285, Mail Stop 188E
2 West Reid Street
Hampton, VA 23681-2199
Work Voice: (757) 864-1437  FAX: (757) 864-4385   Personal Cell: (757) 371-4848
*******************************************************************************

**Comment by zbeekman** [comment]
@singleterry you're welcome to clone this branch, but if you're not interested in doing so or up for the task, then I will be trying to get a release out this weekend ahead of SC.

**Comment by zbeekman** [comment]
I tested locally on macOS and the gcc download succeeds:

```
./install.sh --package gcc
```

LGTM

**Comment by singleterry** [comment]
Hello,

I can wait until the next version.  It would also be nice if the setup.csh (forgot number of the issue) was fixed too!

Robert

*******************************************************************************
Robert C. Singleterry Jr., Ph.D.
Research Engineer and NASA Administrator’s Fellow (Cohort 6: 2002-2004)
Durability, Damage Tolerance, & Reliability Branch
Langley Research Center, National Aeronautics and Space Administration
Building 1205, Room 285, Mail Stop 188E
2 West Reid Street
Hampton, VA 23681-2199
Work Voice: (757) 864-1437  FAX: (757) 864-4385   Personal Cell: (757) 371-4848
*******************************************************************************

**Comment by zbeekman** [comment]
@singleterry I'm working on #607 and #584 (setup.csh) but I could use some more information from you. Since the values are scripted, and I'm not a csh user, it's not completely apparent what needs to change from the way things are now. A diff between what you currently get and what you want would be extremely helpful.

**Comment by singleterry** [comment]
Hello,

To be complete, sent in last email ☺

Robert

*******************************************************************************
Robert C. Singleterry Jr., Ph.D.
Research Engineer and NASA Administrator’s Fellow (Cohort 6: 2002-2004)
Durability, Damage Tolerance, & Reliability Branch
Langley Research Center, National Aeronautics and Space Administration
Building 1205, Room 285, Mail Stop 188E
2 West Reid Street
Hampton, VA 23681-2199
Work Voice: (757) 864-1437  FAX: (757) 864-4385   Personal Cell: (757) 371-4848
*******************************************************************************

**Pull request merged**
