### PR TITLE
Fix #427 on gcc-8 and above.

### LINKED ISSUE #427: Defect: remote indirect addressing does not work
[issue stat img]: https://img.shields.io/issuestats/i/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square

| Avg response time              |
|:------------------------------:|
| ![Issue Stats][issue stat img] |

Is remote indirect addressing supposed to work as of the current development status? 
The key statement is 
```
    xv(loc_idx(1:nhl,ip)) = xv(rmt_idx(1:nhl,ip))[xchg(ip)]
```
which is a (very) simplified version of the so-called halo exchange procedure. 
Without remote indirect addressing I am forced to use a two-sided approach, with packing/transfer/unpacking. 
On a related note, how is the implementation going to handle this? Is there any hope that this will be efficient? E.g., are the indices going to travel across the network? Is this going to be translated into multiple accesses? That would kill performance, hence preventing the use of 1-sided in a very important scenario, PDEs on unstructured meshes. 

# Defect/Bug Report #

- OpenCoarrays Version: 1.9.0
- Fortran Compiler:  GNU 6.3.0, 7.1.0 and 8.0.0
- C compiler used for building lib: GNU
- Installation method: cmake
- Output of `uname -a`:Linux sow768056c-li.soe.cranfield.ac.uk 2.6.32-696.6.3.el6.x86_64 #1 SMP
- MPI library being used: MPICH 3.2.0 
- Machine architecture and number of physical cores: Intel 8 cores
- Version of CMake: 

## Observed Behavior ##
```
e802756@sow768056c-li [103] 12:04 PM [testIndirect] caf --version

OpenCoarrays Coarray Fortran Compiler Wrapper (caf version 1.9.0)
Copyright (C) 2015-2016 Sourcery, Inc.

OpenCoarrays comes with NO WARRANTY, to the extent permitted by law.
You may redistribute copies of OpenCoarrays under the terms of the
BSD 3-Clause License.  For more information about these matters, see
the file named LICENSE.

e802756@sow768056c-li [104] 12:22 PM [testIndirect] gfortran -v
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/home/opt/gnu/8.0.0/bin/../libexec/gcc/x86_64-pc-linux-gnu/8.0.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../gcc/configure --prefix=/opt/gnu/8.0.0 --enable-languages=c,c++,fortran : (reconfigured) ../gcc/configure --prefix=/opt/gnu/8.0.0 --enable-languages=c,c++,fortran : (reconfigured) ../gcc/configure --prefix=/opt/gnu/8.0.0 --enable-languages=c,c++,fortran : (reconfigured) ../gcc/configure --prefix=/opt/gnu/8.0.0 --enable-languages=c,c++,fortran : (reconfigured) ../gcc/configure --prefix=/opt/gnu/8.0.0 --enable-languages=c,c++,fortran,lto --no-create --no-recursion : (reconfigured) ../gcc/configure --prefix=/opt/gnu/8.0.0 --enable-languages=c,c++,fortran,lto --no-create --no-recursion : (reconfigured) ../gcc/configure --prefix=/opt/gnu/8.0.0 --enable-languages=c,c++,fortran,lto --no-create --no-recursion : (reconfigured) ../gcc/configure --prefix=/opt/gnu/8.0.0 --enable-languages=c,c++,fortran,lto --no-create --no-recursion : (reconfigured) ../gcc/configure --prefix=/opt/gnu/8.0.0 --enable-languages=c,c++,fortran,lto --no-create --no-recursion : (reconfigured) ../gcc/configure --prefix=/opt/gnu/8.0.0 --enable-languages=c,c++,fortran,lto --no-create --no-recursion : (reconfigured) ../gcc/configure --prefix=/opt/gnu/8.0.0 --enable-languages=c,c++,fortran,lto --no-create --no-recursion : (reconfigured) ../gcc/configure --prefix=/opt/gnu/8.0.0 --enable-languages=c,c++,fortran,lto --no-create --no-recursion
Thread model: posix
gcc version 8.0.0 20170801 (experimental) (GCC)
e802756@sow768056c-li [102] 12:04 PM [testIndirect] cafrun -np 4 ./ind_test_gnu80 
1: From halo exchange :   1.    2.    3.    4.    5.    6.    7.    8. :   0.    0.
2: From halo exchange :   9.   10.   11.   12.   13.   14.   15.   16. :   0.    0.    0.    0.
3: From halo exchange :  17.   18.   19.   20.   21.   22.   23.   24. :   0.    0.    0.    0.
STOP 
STOP 
STOP 
4: From halo exchange :  25.   26.   27.   28.   29.   30.   31.   32. :   0.    0.
STOP 
```
## Expected Behavior ##
With Intel  I get: 
```
[e802756@delta-login-1 testIndirect]$ ifort --version
ifort (IFORT) 17.0.3 20170404
Copyright (C) 1985-2017 Intel Corporation.  All rights reserved.
[e802756@delta-login-1 testIndirect]$ ./ind_test_intel 
1: From halo exchange :   1.    2.    3.    4.    5.    6.    7.    8. :   9.   10.
2: From halo exchange :   9.   10.   11.   12.   13.   14.   15.   16. :   7.    8.   17.   18.
3: From halo exchange :  17.   18.   19.   20.   21.   22.   23.   24. :  15.   16.   25.   26.
4: From halo exchange :  25.   26.   27.   28.   29.   30.   31.   32. :  23.   24.
```
## Steps to Reproduce ##
Compile the attached file & run 
Is this an OC issue, a GFORTRAN issue,  or both?

```program tst_ind_1
  use iso_fortran_env
  implicit none
  integer, parameter :: nloc=8, nhl=2, ivsize=nloc+2*nhl
  real    :: xv(ivsize)[*]
  integer :: rmt_idx(2,2), loc_idx(2,2)
  integer, allocatable :: xchg(:)
  integer :: nrcv, me, np, nxch, i, ip, iv
  character(len=120) :: fmt

  me = this_image()
  np = num_images()
  
  if (np==1) then
    !    allocate(xchg(0))
    xchg = [ integer :: ]
    
  else if (me == 1) then
    xchg = [me+1]
  else if (me == np) then
    xchg = [me-1]
  else
    xchg = [me-1, me+1]
  end if
  nxch = size(xchg)
  nrcv = nxch * nhl 

  
  xv(1:nloc) = [(i,i=(me-1)*nloc+1,me*nloc)]
  iv = nloc + 1
  do ip=1, nxch
    loc_idx(1:nhl,ip) = [ (i,i=iv,iv+nhl-1) ]
    if (xchg(ip) == me-1) then
      rmt_idx(1:nhl,ip) = [ (i,i=nloc-nhl+1,nloc) ]
    else
      rmt_idx(1:nhl,ip) = [ (i,i=1,nhl) ]
    end if
    iv = iv + nhl
  end do

  sync images(xchg)
  iv = nloc + 1
  do ip=1, nxch
    xv(loc_idx(1:nhl,ip)) = xv(rmt_idx(1:nhl,ip))[xchg(ip)]
  end do
  
  do ip=1, np
    sync all
    if (ip == me) then
      write(fmt,*) '( i0,a,',nloc,'(f5.0,1x),a,',nrcv,'(f5.0,1x) )'
      write(*,fmt) me,': From halo exchange :',xv(1:nloc),':',xv(nloc+1:nloc+nrcv)
    end if
  end do
  stop

end program tst_ind_1
```

### PR DESCRIPTION
**Pull request by vehre**
[links]:#
[contributing guidelines]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md
[issue]: https://github.com/sourceryinstitute/OpenCoarrays/issues
[PR response img]: https://img.shields.io/issuestats/p/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square
[coverage]: https://img.shields.io/codecov/c/github/sourceryinstitute/OpenCoarrays/master.svg?style=flat-square

|  Avg response time                |  coverage on master         |
|:---------------------------------:|:---------------------------:|
| ![Issue Stats][PR response img]   | ![Codecov branch][coverage] |

## Summary of changes ##

This patch fixes OpenCoarrays sendget_by_ref() operator by using the
types of src and dst during execution. These types are only handed to
the function by a gcc >= 8.

Fixes #427.

## Rationale for changes ##

Get it working.

## Additional info and certifications ##

This pull request (PR) is a:

- [x] Bug fix
- [ ] Feature addition
- [ ] Other, Please describe:

### I certify that ###

- [x] I reviewed and followed the [contributing guidelines], including
      - Increasing test coverage for all feature-addition PRs
      - Increasing test coverage for all bug-fix PRs for which there
        does not already exist a related test that failed before the PR
      - At least maintaining test coverage for all other PRs
      - Ensuring that all tests pass when run locally 
      - Naming PR  to indicate work in progress (WIP) and to attach the PR
        to the appropriate bug report or feature request [issue]
      - White space (no trailing white space or white space errors may
        be introduced)
      - Commenting code where it is non-obvious and non-trivial
      - Logically atomic, self consistent and coherent commits
      - Commit message content
      - Waiting 24 hours before self-approving the PR to give another
        OpenCoarrays developer a chance to review my proposed code

### CODE REVIEW

**Comment by zbeekman** [comment]
@vehre tests fail with GCC 7: https://travis-ci.org/sourceryinstitute/OpenCoarrays/jobs/373475422

Apple tests are failing due to build config, merging PR #526 will sort those out. I'm going to change the build order to build debug config first which should be much more helpful now when tests fail since I have added the -D define that prints extra debug output.

**Comment by zbeekman** [comment]
@verhe Can I merge degub-config-fix from PR #526 into this branch, or do you want to work on resolving the test failures for GCC 7 first? Let me know how to help.

**Comment by vehre** [comment]
Your gcc-7/-6/-5 gfortran needs to have the patch from https://gcc.gnu.org/bugzilla/show_bug.cgi?id=85507 in it, or it will not compile.

**Comment by zbeekman** [comment]
@verhe, OK, but in the meantime we need to put guards in at least for the gcc 7 version to allow compilation with 7.1 - 7.3.

**Comment by vehre** [comment]
That's in the build-system. That's your domain.

**Comment by zbeekman** [comment]
@vehre yes I agree the build system is my domain. However, I don't see any `#ifdef`s in the code saying which features should be turned on or off for gcc >= 7.4. Right now we have >= 7 and >= 8 `#ifdef`s. Either we need a new `#ifdef` handling the case where 7.1 <= gcc < 8 or any code not compatible with 7.1-7.3 (and 6.1-6.4) should be lumped in with a `#ifdef GCC_GE_8`. But the first technique would be better to support the fixes in GCC 7 >= 7.4 when they do come out.

**Comment by vehre** [comment]
There shouldn't be any specific guards in the source. The issue with the gfc_dependency() failure was introduced last weekend by me backporting pr81773. It will be fixed as soon as pr85507 has been accepted. So hopefully we just see the compile issues with he current state and gcc 8.0.0.

**Comment by zbeekman** [comment]
So pr81773 will be back-ported to the 6 and 7 branches but will it make it
into e.g. 7.3.1 or just 7.4?

**Comment by vehre** [comment]
I don't know at the moment. I first need the review.

**Comment by scrasmussen** [comment]
Initially everything in the pull request code looks good. It also fixed [issue-518](https://github.com/sourceryinstitute/OpenCoarrays/issues/518), so I'm happy with that. It's evening here and I'm falling asleep at my desk so I can dig deeper into it tomorrow. @rouson I'm not part of the maintainers group so I can't do the code-review/pullapprove

**Comment by rouson** [comment]
@scrasmussen unless anyone desires otherwise, please merge this once you have reviewed and approved this.  Given that this fixes #518, which is the only remaining regression caused by GCC 8.1.0, I will submit a separate pull request that makes GCC 8.1.0 the default version that the OpenCoarrays installer builds.  The same pull request will also patch GCC 8.1.0 before building it.  If it's not too difficult, the new pull request will also test `gfortran` if the user overrides the default.  The test will detect any unpatched GCC 8.1.0 installation.

**Comment by zbeekman** [comment]
@rouson: I object! We need to add #ifdef guards for GCC 7.1-7.3! If you take a look at the CI builds, you'll notice it's broken there. There may be some additional breakage in CI on macOS due to the release of GCC 8, but this PR is broken in GCC 7.1, 7.2, 7.3. This needs fixing before it can be merged. Someone, @verhe ideally, needs to either #ifdef guard the portions that break 7.1-7.3 or figure out an alternate solution

**Comment by rouson** [comment]
@zbeekman  Sorry for not putting more detail in my message.  @scrasmussen mentioned the need for `#ifdef` guards for GCC 7 during the call this morning and agreed to work on those so that was the reason I assigned this issue to him.  He also agreed to ping @vehre for guidance.  If there's an issue that tracks the CI problems on macOS, please insert a link to it in a comment on this issue.  Thanks for your input.

**Comment by rouson** [comment]
@scrasmussen Please add a comment with the names of the failing tests (19, 52, 53) and let us know whether you have the `OPENCOARRAYS_DEVELOPER` environment variable set because that affects which tests run and the test numbering will vary depending on which tests run.

**Comment by zbeekman** [comment]
@scrasmussen: Can we merge in master to this PR, to update it? Also, it is possible that those tests shouldn't be run with 7.1-7.3...

@vehre Can you please comment: Should we expect

- `19:alloc_comp_send_convert_nums`
- `52:put-allocatable-coarray-comp`
- `53:get-put-allocatable-comp`

to run and pass with 7.1-7.3?

**Comment by scrasmussen** [comment]
I just merged my fixes by adding #ifdefs, so if `gcc 7.3` is being used, the old code (pre this pull request) is being used. This was done because all tests from running `make check` passed then, and now they are passing again for `gcc 7.3`. Test `alloc_comp_multidim_shape` is still failing with `gcc 8.1.1`, like before. `OPENCOARRAYS_DEVELOPER` is not set.

@zbeekman I am still interested in seeing what the travis ci reveals but I feel good right now about merging this into master.

**Comment by rouson** [comment]
LGTM

I confirm that the branch in this PR tests cleanly when built inside the Sourcery Institute Linux virtual machine (VM) with an appropriately patched GCC 8.1.0, i.e., the only failure with OPENCOARRAYS_DEVELOPER=ON is the one known issue #511.   Furthermore, all  tests pass inside the VM with GCC 7.3.0.  And last, I have also confirmed that all tests pass with GCC 6.4.0 on a Linux system at the University of Oregon.  And I just noticed that the Travis-CI tests confirm my GCC 6 & 7 results so.

**Comment by zbeekman** [comment]
Why did you close this?

**Comment by zbeekman** [comment]
I think you meant to merge. I'm going to merge now.

**Pull request merged**
