### PR TITLE
Fix opencoarrays_version in windows-install.sh

### PR DESCRIPTION
**Pull request by rouson**
[links]:#
[contributing guidelines]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md
[issue]: https://github.com/sourceryinstitute/OpenCoarrays/issues
[PR response img]: https://img.shields.io/issuestats/p/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square
[coverage]: https://img.shields.io/codecov/c/github/sourceryinstitute/OpenCoarrays/master.svg?style=flat-square

|  Avg response time                |  coverage on master         |
|:---------------------------------:|:---------------------------:|
| ![Issue Stats][PR response img]   | ![Codecov branch][coverage] |

## Summary of changes ##

Updated the definition of `opencoarrays_version` in `windows-install.sh` to reflect a months-old change in version numbering.

## Rationale for changes ##

Build on Windows Subsystem for Linux was failing.

## Additional info and certifications ##

This pull request (PR) is a:

- [X] Bug fix
- [ ] Feature addition
- [ ] Other, Please describe:

### I certify that ###

- [X] I reviewed and followed the [contributing guidelines], including
      - Increasing test coverage for all feature-addition PRs
      - Increasing test coverage for all bug-fix PRs for which there
        does not already exist a related test that failed before the PR
      - At least maintaining test coverage for all other PRs
      - Ensuring that all tests pass when run locally 
      - Naming PR  to indicate work in progress (WIP) and to attach the PR
        to the appropriate bug report or feature request [issue]
      - White space (no trailing white space or white space errors may
        be introduced)
      - Commenting code where it is non-obvious and non-trivial
      - Logically atomic, self consistent and coherent commits
      - Commit message content
      - Waiting 24 hours before self-approving the PR to give another
        OpenCoarrays developer a chance to review my proposed code

### CODE REVIEW

**Comment by rouson** [comment]
@zbeekman I went back to commits as old as late April and found that the Windows installer has been broken for a rather long time.   This caused me to realize that we could actually be testing this script in Travis-CI.  Because the script runs under Windows Subsystem for Linux, it's actually just a bash script that expects to run on Ubuntu 16.04 or later.  There is nothing in the script specific to Windows.  Please set up for Travis-CI to test this script if it's easy to do so.  Let me know if I should create an issue for this.

**Comment by zbeekman** [comment]
ah, sorry, this was my fault. I  made the change that originally caused this and neglected to update the windows script.

LGTM

**Comment by zbeekman** [comment]
The shebang at the start of the file is wrong: https://github.com/sourceryinstitute/OpenCoarrays/pull/441/files#diff-761c977a48b8e2a4ee665b286772ca5dR1

missing a `!` after the leading `#`

also, shellcheck has many warnings

**Comment by zbeekman** [comment]
also style issues:

```
$ ./developer-scripts/style.pl windows-install.sh
windows-install.sh[112]: [ -z "${LOG_LEVEL:-}" ] && emergency "Cannot continue without LOG_LEVEL. "
windows-install.sh[115]: if [[ "${arg_d}" == "${__flag_present}" ]]; then[ ]
windows-install.sh[117]:    if [ "$(( LOG_LEVEL < print_debug_only ))" -ne 0 ]; then
windows-install.sh[147]: export this_script="$(basename "$0")"
windows-install.sh[161]:   opencoarrays_version=$text_before_language_keyword
windows-install.sh[166]: export build_path="${OPENCOARRAYS_SRC_DIR%/}"/prerequisites/builds/opencoarrays/$opencoarrays_version
windows-install.sh[197]:   if [[ $major_release -lt 16  ]]; then
windows-install.sh[199]:   elif [[ $major_release -eq 16  ]]; then
windows-install.sh[200]:     if [[ $minor_release -lt "04"  ]]; then
windows-install.sh[209]:     info "$opencoarrays_version"
windows-install.sh[230]: [ ]
windows-install.sh[233]:   if ! type "$CMAKE" >& /dev/null; then
windows-install.sh[236]:   if ! type "$CXX" >& /dev/null; then
windows-install.sh[239]:   if ! type "$FC" >& /dev/null; then
windows-install.sh[242]: [  ]
windows-install.sh[271]: [  ]
windows-install.sh[274]:   if [[ -d "$build_path" ]]; then
windows-install.sh[275]:     rm -rf "$build_path"
windows-install.sh[277]:   mkdir -p "$build_path"
windows-install.sh[278]:   cd "$build_path"
windows-install.sh[280]:   info "FC=\"$FC\" CC=\"$CC\"  \"$CMAKE\" \"$OPENCOARRAYS_SRC_DIR\" -DCMAKE_INSTALL_PREFIX=\"$install_prefix\""
windows-install.sh[281]:   FC="$FC" CC="$CC" "$CMAKE" "$OPENCOARRAYS_SRC_DIR" -DCMAKE_INSTALL_PREFIX="$install_prefix"
windows-install.sh[283]:   info "make -j $arg_j"
windows-install.sh[284]:   make -j $arg_j
windows-install.sh[288]:   if [[ -f "$install_prefix"/lib/libcaf_mpi.a && -f "${install_prefix}/bin/caf"  && -f "${install_prefix}/bin/cafrun"  ]]; then
windows-install.sh[290]:     info "$install_prefix"
windows-install.sh[293]:     emergency "$install_prefix"
windows-install.sh[296]:   loopback_line=`grep $NAME /etc/hosts`
windows-install.sh[299]:     info "127.0.0.1 $NAME"
```

**Comment by zbeekman** [comment]
@rouson hmmm it also appears that git wasn't configured correctly, so it didn't record the author info correctly. As a consequence, it thinks that the CLA needs to be signed again. I can probably forcibly fix this myself.

**Comment by zbeekman** [comment]
yeah, it looks like you didn't configure git properly in a new environment:

```
Author:  <rouson@DESKTOP-S9SB06H.localdomain>
 Date:   Fri Sep 1 17:54:31 2017 -0700
```

**Comment by zbeekman** [comment]
LGTM

let's merge after tests run & pass

**Pull request merged**
