### PR TITLE
Add FAQ.md frequently asked questions file.

### PR DESCRIPTION
**Pull request by zbeekman**
[links]:#
[contributing guidelines]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md
[issue]: https://github.com/sourceryinstitute/OpenCoarrays/issues
[PR response img]: https://img.shields.io/issuestats/p/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square
[coverage]: https://img.shields.io/codecov/c/github/sourceryinstitute/OpenCoarrays/master.svg?style=flat-square

|  Avg response time                |  coverage on master         |
|:---------------------------------:|:---------------------------:|
| ![Issue Stats][PR response img]   | ![Codecov branch][coverage] |

## Summary of changes ##

Added a FAQ

## Rationale for changes ##

Adhere to DRY, improve documentation

## Additional info and certifications ##

This pull request (PR) is a:

- [ ] Bug fix
- [X] Feature addition
- [ ] Other, Please describe:

### I certify that ###

- [X] I reviewed and followed the [contributing guidelines], including
      - Increasing test coverage for all feature-addition PRs
      - Increasing test coverage for all bug-fix PRs for which there
        does not already exist a related test that failed before the PR
      - At least maintaining test coverage for all other PRs
      - Ensuring that all tests pass when run locally 
      - Naming PR  to indicate work in progress (WIP) and to attach the PR
        to the appropriate bug report or feature request [issue]
      - White space (no trailing white space or white space errors may
        be introduced)
      - Commenting code where it is non-obvious and non-trivial
      - Logically atomic, self consistent and coherent commits
      - Commit message content
      - Waiting 24 hours before self-approving the PR to give another
        OpenCoarrays developer a chance to review my proposed code

### CODE REVIEW

**Comment by zbeekman** [comment]
I have added your suggestions.

**Comment by rouson** [comment]
Thanks.  I'll pull in the latest changes and start from there.

**Comment by rouson** [comment]
I'm just trying to add a table of contents.  It's a pain, but will be especially useful as the file grows.

**Comment by zbeekman** [comment]
There are tools to generate ToC. I used to have an Emacs package to do
this. Btw, I finished my section of the March MSLR, we should get that out
ASAP.

**Comment by rouson** [comment]
Great tip.  This looks good: https://github.com/ekalinin/github-markdown-toc.  I'll try it.

**Comment by rouson** [comment]
The tool worked with just one minor tweak.  Thanks!  I had to look up [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).  Nice concept!

**Comment by rouson** [comment]
LGTM

**Pull request merged**
