### PR TITLE
Small cleanups

### LINKED ISSUE #79: Review installation logic, files and directories
- Add an `uninstall` target so users can easily remove OCA (now #89)
- Investigate which files are being installed, to where, and why
  - right now it seems that some of the tests are being installed; these should probably only be run at build time `cmake .. && make && make test && make install` is the canonical order of operations... no need to install tests.
- Fortran and .mod files complicate this a little bit, when on systems with multiple fortran compilers. I developed what I think is a very good system for https://github.com/jacobwilliams/JSON-Fortran

@zbeekman I'm adding an item to this list:
- Write unit tests for the installation scripts.  

I started this with a [commit](https://github.com/sourceryinstitute/opencoarrays/commit/91f8fd1cc1ac3373b1ab6a46d91aad6c25c2d492) pushed last night.  The motivation was that my work on inserting `find_or_install gcc` near the beginning of [build_opencoarrays.sh](https://github.com/sourceryinstitute/opencoarrays/blob/master/prerequisites/install-functions/build_opencoarrays.sh) necessitates changing some stack management in [find_or_install.sh](https://github.com/sourceryinstitute/opencoarrays/blob/master/prerequisites/install-functions/find_or_install.sh) and the stack function I'll most likely use is one that I wrote, but hadn't sufficiently tested. The new tests have already identified some issues in stack.sh and helped define the boundaries of what is safe to use.

### LINKED ISSUE #297: libfft_sse.a fails to link on `mpich-docker-image`
Attn: @rouson 

When trying to build the naiver-stokes integration test, the linker fails with the following output:

```
/usr/bin/gfortran   -Wl,-rpath  -Wl,/opt/mpich/3.1.4/gnu/6.2.1/lib  -Wl,--enable-new-dtags  -g CMakeFiles/coarray_navier_stokes.dir/coarray-shear_coll.F90.o  -o coarray_navier_stokes -Wl,-rpath,/opt/mpich/3.1.4/gnu/6.2.1/lib  ../../../../../../src/tests/integration/pde_solvers/navier-stokes/libfft_sse.a ../../../../mpi/libcaf_mpi.a /opt/mpich/3.1.4/gnu/6.2.1/lib/libmpi.so /opt/mpich/3.1.4/gnu/6.2.1/lib/libmpifort.so /opt/mpich/3.1.4/gnu/6.2.1/lib/libmpi.so /opt/mpich/3.1.4/gnu/6.2.1/lib/libmpifort.so
/usr/bin/ld: ../../../../../../src/tests/integration/pde_solvers/navier-stokes/libfft_sse.a(trig.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../../../../src/tests/integration/pde_solvers/navier-stokes/libfft_sse.a(plan.o): relocation R_X86_64_32 against `.rodata.str1.4' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
```

I'm a bit perplexed as to why this happens... the linker is saying that `-fPIC` should be added, but, I thought that the FFT libraries were hand written in assembly... Perhaps this is just a "won't fix" and we should move on...

### PR DESCRIPTION
**Pull request by zbeekman**
This branch name has become a bit of a misnomer... I have lumped together a number of fixes and enhancements... in general this is probably a bad practice, but I vote we let it slide for now...

Add badges etc to readme, adjust regression tests links to reflect closure of issues, and add co_reduce regression test, even though it appears it was never a regression to begin with.

 - Fixes #79
 - Fixes  #297 
 - Add regression test for #243 
 - Add regression for #172 (currently set to pass when test fails)
 - Migrates to use of a `.VERSION` file to make parsing easier for scripts and allow extra comments
 - Adds auto-upload of release assets upon tagging with git, but requires that the tag is PGP signed (`git tag -s <tag> [tree-ish]`)
 - This should compute the SHA 256 checksum and create a detached signature of the cryptographic SHA 256 checksum with an encrypted GPG subway I uploaded to the repo/travis. 🔮 🎩 🐇

### CODE REVIEW

**Comment by zbeekman** [comment]
These commits need to be rebased and cleaned up before merging... Also I set CMake/CTest to indicate pass status even when regression 172 fails... I did this so that I could examine and compare codecov.io output between the passing and failing tests in an attempt to localize the bug if it's in the library.

**Comment by zbeekman** [comment]
With `value` instead of `intent(in)` here are the coverage changes: https://codecov.io/gh/sourceryinstitute/opencoarrays/compare/882c371d4d7e84364eb7adfba4b4f8d840e3f398...cb9f040bfc7543424a637a43fb447fbbe605a0f8/changes

vs

https://codecov.io/gh/sourceryinstitute/opencoarrays/compare/882c371d4d7e84364eb7adfba4b4f8d840e3f398...1a0e3b7edb6867d9e9371cbd9ed1d8f5b3dd2010/changes with `intent(in)`

**Comment by zbeekman** [comment]
lgtm

**Comment by zbeekman** [comment]
Need to account for older CMake where `CMAKE_Fortran_COMPILER_VERSION` is missing....

**Comment by zbeekman** [comment]
LGTM

**Comment by zbeekman** [comment]
@rouson: I've added a regression test for #172, but it's still failing. To cope with this, I've set it so that failing indicates success (so that users won't see test failures because it's a known issue...) I'd like to merge this PR, but I could split that test out into a separate one. What do you think? Would you be OK with merging this PR with the failing regression for #172 but have it report a "PASS" status when it fails?

**Comment by zbeekman** [comment]
I'm going to go for it... we can always factor out the #172 regression test later.

**Comment by vehre** [comment]
Is there no way to set a test to expect to fail?

**Comment by zbeekman** [comment]
That's what it is now. But then when it's fixed it will report a failure.
It's a logical not/inverse operation.

**Comment by rouson** [comment]
@zbeekman Hopefully you saw my message sent via Hangouts.  If a failing test degrades user confidence, then I believe that a false positive would degrade user confidence even more.  Moreover, I am highly unlikely to remember this exchange 6 months from now when a user reports a related problem and then I spend time trying to track down the cause, only to realize the cause has been under my nose all along, but I forgot about it because I've ben lulled into a false sense of security.   Probably it's best to set up CMake so that there are a group of tests that are cordoned off as known failures and not run unless a flag is passed to run them.  They should probably also be listed somewhere such as in our [Known Issues](https://github.com/sourceryinstitute/opencoarrays/blob/master/STATUS.md) page, which actually might be obsolete at this point because we haven't maintained it.  So probably an even better approach would be to have a Known Issues milestone under which we would the issue numbers related to failing tests and name the tests.  I'd say almost anything is better than having a test falsely report success.

**Comment by zbeekman** [comment]
This is clearly the correct way to do it. The only question is: when do we turn on the known failures? During CI tests? For the users by default (with a message telling them it's a known deficiency?) I'm inclined to take the latter approach, in the interest of transparency 

As for the known issues page, we should ensure that we have an open issue for each issue and a link to the issues page.

**Comment by rouson** [comment]
@zbeekman Your suggestion sounds good to me as long as the users see a message indicating that these are known failures.  Ideally the message would even include a URL to the list of known failures.  For Travis-CI, we would build with something like

cmake .. -DBUILD_KNOWN_FAILURES=TRUE

where the above flag would default to FALSE or would be explicitly set to FALSE for CI.

**Comment by zbeekman** [comment]
> Your suggestion sounds good to me as long as the users see a message indicating that these are known failures.

I 100% agree... My thinking is this: In the known failures test we output clear messages with URLs pointing to the issue tracker pages saying these are known deficiencies that we are working to resolve. Failing tests are turned on by default, and if the user is installing via `install.sh` we can ensure that we `export CTEST_OUTPUT_ON_FAILURE=1` and have any calls to `ctest` with the `--output-on-failure` flag. This way they will see the warning message. We can also include a warning in the CMake configure script informing them that we have turned on tests with known failures and giving them instructions on how to turn those off.

As long as the failures are runtime failures we should always build them, since compilation in and of itself is a smoke test.

On Travis-CI, however, I don't think we should run tests known to fail so that we can continue our workflow of finding new bugs and issues, without the noise coming from bugs we already know about. Otherwise the known issues would obfuscate new ones and coding errors/typos etc.

**Pull request merged**
