### PR TITLE
Fix inconsequential stack sh errors

### PR DESCRIPTION
**Pull request by rouson**

### CODE REVIEW

**Comment by zbeekman** [comment]
:ballot_box_with_check: :ok_hand:

**Comment by zbeekman** [comment]
:ok_hand:

**Comment by zbeekman** [comment]
Was this ever merged into master as well? (I'm on a plane, on my phone, using an iPhone app so it's hard for me to tell at the moment)

**Comment by rouson** [comment]
From the network graph, it appears it was not.  I'll try to do that today. I think there were merge conflicts that needed to be resolved at the command line.

**Comment by zbeekman** [comment]
Ok I can take a look too. It can be harder/more complicated to merge into `master` **_after_** merging into `devel` rather than *before*. I'm waiting to take off now so I may not be able to take a look until tomorrow.

**Comment by rouson** [comment]
I'm trying to do the merge.  If I don't succeeds, let's talk tomorrow while you look at it so I can see what you do.

**Pull request merged**
