### PR TITLE
Fixes #279, test enabled on GCC 7 when it shouldn't be

### LINKED ISSUE #279: check_remote_alloced_comp_1.f90 hangs in VM
@vehre 

Test #9 [check_remote_alloced_comp_1.f90](https://github.com/sourceryinstitute/opencoarrays/blob/master/src/tests/unit/init_register/check_remote_alloced_comp_1.f90) hangs in the current version of the virtual machine, which has a gfortran build from 2 days ago.  This appears to be a new test that you created 3 days ago.  

I just uploaded the latest version of the virtual machine today.  It has GCC compilers dated 20161215.

### PR DESCRIPTION
**Pull request by zbeekman**
Appologies to @rouson and @vehre for messing this up....

This should fix it though.

### CODE REVIEW

**Comment by zbeekman** [comment]
All tests passed before updating branch by merging master after #278 was merged.

So this 

looks good to me

**Comment by zbeekman** [comment]
rejected By @rouson, if I understood correctly: https://github.com/sourceryinstitute/opencoarrays/issues/279#issuecomment-267779763

**Comment by vehre** [comment]
Imho this should be merged. The testcase can't work w/o #260.

**Comment by zbeekman** [comment]
I agree that the test won't work w/o #260, but merging or not merging this PR won't change that... It's a matter of getting #29 taken care of to decide more carefully what gets merged into master and when.

Our model approximates a continuous deployment scenario where master should be as close to stable and deployable as possible.

**Comment by zbeekman** [comment]
PR #281 set a better resolution to this issue... closing.

**Pull request closed without merging**
