### PR TITLE
Fix bug & improve Windows support

### LINKED ISSUE #435: Defect: MPI_Type_extent, type of 2nd argument is pointer to MPI_Aint
# Defect/Bug Report #

Defect: MPI_Type_extent, type of 2nd argument is pointer to MPI_Aint
- OpenCoarrays Version: 1.9.1
- Fortran Compiler: GNU Fortran (x86_64-posix-seh-rev2, Built by MinGW-W64 project) 7.1.0
- C compiler used for building lib: gcc (x86_64-posix-seh-rev2, Built by MinGW-W64 project) 7.1.0
- Installation method: Manual, Win7-64
- Output of `ver`: Microsoft Windows [Version 6.1.7601]
- MPI library being used: Intel(R) MPI Library for Windows* OS, Version 2017 Update 3 Build 20170405
- Machine architecture and number of physical cores:  Intel Haswell i7, 4 cores, 8 threads
- Version of CMake: N/A

## Observed Behavior ##

```
C:\TEMP\oca\src_1.9.1\mpi>gcc --version
gcc (x86_64-posix-seh-rev2, Built by MinGW-W64 project) 7.1.0
```

- `-I..` used to find `libcaf.h`
- `-I../..` used to find `mpi.h`
- `-D_POSIX` used to find `SIGKILL` in `signal.h`
- `-DALLOCA_MISSING` because it is missing
- `-DUSE_GCC` for correct typedef of `MPI_Aint` in `mpi.h` (`long long int`)
- `-g -Og` for debugging with `gdb`
- `-m64` to give an error message if compile attempted with Win32 version of mingw-w64 gcc

```
C:\TEMP\oca\src_1.9.1\mpi>gcc -g -m64 -DGCC_GE_7 -DPREFIX_NAME=_gfortran_caf_ -DUSE_FAILED_IMAGES -DALLOCA_MISSING -D_POSIX -DUSE_GCC -Og -c mpi_caf.c -I .. -I ../..
mpi_caf.c: In function 'redux_char_by_reference_adapter':
mpi_caf.c:4140:30: warning: passing argument 2 of 'MPI_Type_extent' from incompatible pointer type [-Wincompatible-pointer-types]
   MPI_Type_extent(*datatype, &string_len);
                              ^
In file included from mpi_caf.c:44:0:
../../mpi.h:1121:5: note: expected 'MPI_Aint * {aka long long int *}' but argument is of type 'long int *'
 int MPI_Type_extent(MPI_Datatype datatype, MPI_Aint *extent);
     ^~~~~~~~~~~~~~~
```
In linux (which is LP64), the correct typedef of `MPI_Aint` is long int (see `mpi.h` from MPICH 3.2).  For Windows (which is LLP64), the mpi.h from the Intel MPI Windows SDK defines `-DUSE_GCC` to implement the correct typedef of long long int for `MPI_Aint` with GCC.

```
Intel MPI Windows SDK, mpi.h:  int MPI_Type_extent(MPI_Datatype datatype, MPI_Aint *extent);

C:\TEMP\oca\src_1.9.1\mpi>fc /L /N mpi_caf.c mpi_caf.c.original
Comparing files mpi_caf.c and MPI_CAF.C.ORIGINAL
***** mpi_caf.c
 4142:  {
 4143:    MPI_Aint string_len;
 4144:    MPI_Type_extent(*datatype, &string_len);
***** MPI_CAF.C.ORIGINAL
 4142:  {
 4143:    long int string_len;
 4144:    MPI_Type_extent(*datatype, &string_len);
*****
```

# Question #

I posted details of my build (including build of import library for impi.dll) and results at people.tamu.edu/~bmaggard, in case anyone is interested in a native Win64 CAF solution (Win7-64; mingw-w64 gfortran 7.1.0.rev2; Intel MPI Runtime 2017 Update 3; OpenCoarrays-1.9.1).  Execution results are equivalent to building 1.9.1 on linux with install.sh (Fedora 26; gcc-gfortran 7.1.1-3, MPICH 3.2, OpenCoarrays-1.9.1).

For GCC 7.1.0, my question at this time is whether I should be using any/all of the defines:  COMPILER_SUPPORTS_CAF_INTRINSICS, STRIDED, and COMPILER_SUPPORTS_ATOMICS.  Feedback appreciated on this question.

### PR DESCRIPTION
**Pull request by zbeekman**
Based on tales of success by @jbmaggard in issue #435
 Fixes #435
 Error in the type def of an argument to `MPI_Type_extent`
 `long int string_len;` → `MPI_Aint string_len;` on `mpi_caf.c:4140`

[L4140]: https://github.com/sourceryinstitute/OpenCoarrays/blob/f7a5f2ebeaf935a67184a978bc40177e4399b82b/src/mpi/mpi_caf.c#L4140

[links]:#
[contributing guidelines]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md
[issue]: https://github.com/sourceryinstitute/OpenCoarrays/issues
[PR response img]: https://img.shields.io/issuestats/p/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square
[coverage]: https://img.shields.io/codecov/c/github/sourceryinstitute/OpenCoarrays/master.svg?style=flat-square

|  Avg response time                |  coverage on master         |
|:---------------------------------:|:---------------------------:|
| ![Issue Stats][PR response img]   | ![Codecov branch][coverage] |

## Summary of changes ##

Fixed bug with improper type of argument to `MPI_Type_extent` found in #435 

## Rationale for changes ##

Build fails on windows vs MS-MPI using mingw GCC 7.1. Definitely a bug, regardless of whether or not it works on Windows, but add'l changes added to attempt to improve windows support.

## Additional info and certifications ##

This pull request (PR) is a:

- [x] Bug fix
- [ ] Feature addition
- [ ] Other, Please describe:

### I certify that ###

- [x] I reviewed and followed the [contributing guidelines], including
      - Increasing test coverage for all feature-addition PRs
      - Increasing test coverage for all bug-fix PRs for which there
        does not already exist a related test that failed before the PR
      - At least maintaining test coverage for all other PRs
      - Ensuring that all tests pass when run locally 
      - Naming PR  to indicate work in progress (WIP) and to attach the PR
        to the appropriate bug report or feature request [issue]
      - White space (no trailing white space or white space errors may
        be introduced)
      - Commenting code where it is non-obvious and non-trivial
      - Logically atomic, self consistent and coherent commits
      - Commit message content
      - Waiting 24 hours before self-approving the PR to give another
        OpenCoarrays developer a chance to review my proposed code

### CODE REVIEW

**Comment by zbeekman** [comment]
@jbmaggard: I think my latest commit, 111d775ad040a51629cb9cdc66e572c6a12f90f0, is a half decent attempt at system introspection to deal with `-D_POSIX` and `-DUSE_GCC`. For the former I check with CMake if `signal.h` provides `SIGKILL` and if not, I check again passing `-D_POSIX`. If `-D_POSIX` fixes it (regardless of platforms) then it gets passed at compile time. Later I then check for `I_MPI_VERSION` in `mpi.h`. If it's there and the platform is Windows, then I pass `-DUSE_GCC`.

I'm fairly confident that this is a decent approach. There's still the issue of the `impi.dll` interface library, I'll study your notes to try to figure that out, perhaps it can be automatically generated? At any rate, if you're able to test this branch it would be much appreciated, if not, a brief code review with your thoughts on the feasibility of this approach would certainly be appreciated. Even if you don't get to this I'll probably merge if all CI tests pass, since it's closer to a Windows solution than without it.

**Comment by zbeekman** [comment]
LGTM

**Comment by jbmaggard** [comment]
@zbeekman : comments per your request.

Both your testing for -D_POSIX with define of SIGKILL, and inspecting mpi.h for I_MPI_VERSION for -DUSE_GCC both seem sound (LGTM).

impi.dll is installed with the Intel MPI Windows Runtime.  The I_MPI_ROOT environment variable is set to the location where %I_MPI_ROOT\intel64\bin\impi.dll is installed.

libimpi.a is an import library created to interface with impi.dll (the MSYS2/mingw64/ subsystem has both of the utilities needed to create this import library during the build; gendef and dlltool).

-----

I was pleasantly surprised by how far the install.sh got using the MSYS2/MinGW64 command line environment.  It didn't fail until it couldn't find the MPICH installation.  I remember reading that windows-install.sh (for Win10-WSL) is similar to install.sh, except that the parts to get and build GCC and/or MPICH (if needed) has been removed.  I think a similar "msys2-install.sh" running in the MSYS2 MinGW64 bash prompt environment is very possible; which would test for the MSYS2/mingw64/ subsystem verisons of GCC (gcc.exe and gfortran.exe), cmake (cmake.exe), and make (mingw32-make.exe), and test for the Intel MPI Windows runtime (%I_MPI_ROOT%\intel64\binimpi.dll)

I've also been spending some time with cmake tutorials, utilizing the MSYS2/mingw64/ verision of cmake (3.9.1), and so far everything looks good.  This increases my confidence that using cmake to generate a native Win64 libcaf_mpi.a is possible:

OS:  Win64 (7, 8.1, 10)
GCC: MSYS2/mingw64 (currently at 7.2.0, older versions available for install if needed)
cmake:  MSYS2/mingw64 (currently at 3.9.1, older versions available for install if needed)
make: MSYS2/mingw64 (currently at 4.2.1, older versions available for install if needed.
MPI: Intel MPI Windows Runtime (building an import library to impi.dll could be done by cmake)
OpenCoarrays: 1.9.1 (no assumption that MPI_Aint is long int)

MSYS2 provides two ways to approach building a native Win64 app on MSYS2.

1. Use only the tools from the MSYS2/mingw64/ subsystem.  These tools could be run from the Windows Command Prompt if bash is not needed.  The c:\msys64\mingw64\bin folder would need to be in the Windows Command Prompt PATH (and should be the only folder from the c:\msys64 folder tree in the PATH), enabling the MSYS2/mingw64 applications installed.

2. Use the MSYS2/mingw64/ subsystem for the GCC, cmake, and make packages, along with any other needed build tool packages from the MSYS2/msys/ subsystem, with the MSYS/mingw64 GCC generating native Win64 libcaf_mpi.  Using the MSYS2 MinGW64 command line environment provides a bash shell, and allows using other packages from the msys/ subsystem.  How this works is that the MSYS2 MinGW64 command line environment has /mingw64/bin in the PATH ahead of /usr/local/bin:/usr/bin:/bin: putting the MSYS2/mingw64/ tools ahead of the MSYS2/msys/ tools in the PATH.

**Comment by zbeekman** [comment]
Awesome! @jbmaggard thanks so much for  your time, insight, analysis and phenomenally detailed defect report and notes! 💯 🎉

**Comment by rouson** [comment]
@jbmaggard: I would be glad to work with you on a `msys2-install.sh` as you suggest.  If you're interested, then I suggest we set up some time to talk about it and do some interactive pair programming to develop an initial draft.  Time can be booked at https://rouson.youcanbook.me.  If that seems helpful, I could walk you through an overview of the installer.  In fact, if we can reliably detect that the installer is running inside MinGW, then we can just incorporate an automatic invocation of `msys2-install.sh` from `install.sh`.

**Comment by zbeekman** [comment]
@rouson: most of the CMake machinery is there... probably need to add a target to build the `libimpi.a` using `gendef` and `dlltool`. Another interesting question for @jbmaggard: does msys2 have bash >= 3.0? Otherwise we'll need a batch script like you used in your notes.

**Comment by jbmaggard** [comment]
@rouson 

From the MSYS2/msys bash command line:

AUTH+bmaggard@PE-MGR-LAPTOP MSYS ~
$ uname -a
MSYS_NT-6.1 PE-MGR-LAPTOP 2.8.2(0.313/5/3) 2017-07-14 08:19 x86_64 Msys

From the MSYS2/mingw64 bash command line (build a native Win64 libcaf_mpi.a and libimpi.a import library)

AUTH+bmaggard@PE-MGR-LAPTOP MINGW64 ~
$ uname -a
MINGW64_NT-6.1 PE-MGR-LAPTOP 2.8.2(0.313/5/3) 2017-07-14 08:19 x86_64 Msys

In addition to Win7-64 reported above, I have Win8.1-64, and Win10-64 systems, so I'll take a look at the uname -a results on each, and report in a followup comment.

I'll be working my way through install.sh, windows-install.sh, and the cmake over the next week or two, so I will be able to use your time more efficiently, if we decide to go forward with an msys2-install.sh.


@zbeekman 

MSYS2/mingw64 bash command line:

AUTH+bmaggard@PE-MGR-LAPTOP MINGW64 ~
$ echo $PATH
/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows

$ echo $BASH_VERSION
4.4.12(1)-release

AUTH+bmaggard@PE-MGR-LAPTOP MSYS ~
$ bash --version
GNU bash, version 4.4.12(1)-release (x86_64-pc-msys)

Version is the same on both the MSYS2/mingw64 and MSYS2/msys bash command line, because bash is an MSYS2/msys package.  Recall the MSYS2/mingw64 command line has /mingw64/bin first in the path, but since there is no mingw64/ package installed having bash, it falls through to /usr/bin in the path to execute bash.exe from the MSYS2/msys package (not a windows native bash.exe, requires the msys-2.0.dll (partial) POSIX emulation layer)

MSYS2/msys bash command line (used for package management); results excerpted to be concise.

$ pacman -Ss bash
msys/bash 4.4.012-1 (base) [installed]
    The GNU Bourne Again shell
msys/bash-devel 4.4.012-1 (development)
    Bash headers and libraries

I expect one way to use gendef and dlltool to build libimpi.a might be with add_custom_command and add_custom_target.  I thought this example was interesting, https://gist.github.com/socantre/7ee63133a0a3a08f3990

**Comment by zbeekman** [comment]
@jbmaggard Great, thanks for the additional details and help! If we can do it right, the best option would be to bake in the introspection and steps needed for the windows build into CMake. If it only requires minor adjustment, then `install.sh` could handle these cases rather than an extra script. Just food for thought, but less bifurcation of the build system is always better IMO.

**Comment by jbmaggard** [comment]
@zbeekman @rouson 

Here is a first try from a cmake beginner.  Using the MSYS2/mingw64 bash command line.  Not happy about having to create libimpi.a.stamp for a build dependency in add_library, but I haven't yet found another way that works correctly (perhaps set_property could add the dependency after add_library).  Criticism would be appreciated.

On uname -a the only parts that changed on Win10-64 and Win8.1-64 were "6.1 PE-MGR-LAPTOP"

Here are my notes on my CMakeLists.txt build:

$ uname -a
MINGW64_NT-6.1 PE-MGR-LAPTOP 2.8.2(0.313/5/3) 2017-07-14 08:19 x86_64 Msys

$ tree .
.
├── run_cmake.sh
├── run_make.sh
└── src
    ├── CMakeLists.txt
    ├── common
    │   └── caf_auxiliary.c
    ├── extensions
    │   └── opencoarrays.F90
    ├── libcaf.h
    ├── libcaf-gfortran-descriptor.h
    └── mpi
        └── mpi_caf.c

4 directories, 8 files



$ cat ./run_cmake.sh
rm -rf ./build
cmake -Bbuild -Hsrc -G "MSYS Makefiles" -DCMAKE_MAKE_PROGRAM=/mingw64/bin/mingw32-make.exe

$ cat ./run_make.sh
cd build
mingw32-make
#mingw32-make VERBOSE=1
cd ..

$ cat src/CMakeLists.txt
cmake_minimum_required(VERSION 3.9.1)
project("libcaf_impi" NONE)
enable_language(C Fortran)

message("---- Begin: CMAKE Variables")
message("---- SYSTEM=" ${CMAKE_SYSTEM} ", SYSTEM_NAME=" ${CMAKE_SYSTEM_NAME} ", SYSTEM_VERSION=" ${CMAKE_SYSTEM})
message("---- UNIX=" ${UNIX} ", WIN32=" ${WIN32} ", APPLE=" ${APPLE} ", MINGW=" ${MINGW} ", MSYS=" ${MSYS} ", CYGWIN=" ${CYGWIN})
message("---- BORLAND=" ${BORLAND} ", WATCOM=" ${WATCOM} ", MSVC=" ${MSVC})
message("---- C_COMPILER_ID=" ${CMAKE_C_COMPILER_ID} ", COMPILER_IS_GNUCC=" ${CMAKE_COMPILER_IS_GNUCC})
message("---- End: CMAKE Variables")

set(CMAKE_C_FLAGS
        ${CMAKE_C_FLAGS}
        " -g -Og -DPREFIX_NAME=_gfortran_caf_ -DALLOCA_MISSING -D_POSIX -DUSE_GCC -DGCC_GE_7 -DUSE_FAILED_IMAGES"
)

set(CMAKE_Fortran_FLAGS
        ${CMAKE_Fortran_FLAGS}
        " -g -Og -DPREFIX_NAME=_gfortran_caf_ -DALLOCA_MISSING -D_POSIX -DUSE_GCC -DGCC_GE_7 -DUSE_FAILED_IMAGES"
)

include_directories(
        ${CMAKE_SOURCE_DIR}
        ${CMAKE_SOURCE_DIR}/../..
)

add_library(
        caf_impi STATIC
        extensions/opencoarrays.F90
        common/caf_auxiliary.c
        mpi/mpi_caf.c
        ${CMAKE_CURRENT_SOURCE_DIR}/libimpi.a.stamp
)

add_custom_command(
        OUTPUT ${CMAKE_CURRENT_SOURCE_DIR}/libimpi.a.stamp
        MAIN_DEPENDENCY ${CMAKE_CURRENT_BINARY_DIR}/libimpi.a
        COMMAND touch ${CMAKE_CURRENT_SOURCE_DIR}/libimpi.a.stamp
        COMMENT "    * Updating libimpi.a.stamp (touch)"
)

add_custom_command(
        OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/libimpi.a
        MAIN_DEPENDENCY ${CMAKE_CURRENT_BINARY_DIR}/impi.def
        COMMAND dlltool -d impi.def -l libimpi.a -D $ENV{I_MPI_ROOT}/intel64/bin/impi.dll
        COMMENT "   ** Generating libimpa.a import library to impi.dll (dlltool)"
)

add_custom_command(
        OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/impi.def
        MAIN_DEPENDENCY $ENV{I_MPI_ROOT}/intel64/bin/impi.dll
        COMMAND gendef $ENV{I_MPI_ROOT}/intel64/bin/impi.dll
        COMMENT "  *** Generating .def for impi.dll (gendef)"
)

$ . ./run_cmake.sh
-- The C compiler identification is GNU 7.2.0
-- The Fortran compiler identification is GNU 7.2.0
-- Check for working C compiler: C:/msys64/mingw64/bin/gcc.exe
-- Check for working C compiler: C:/msys64/mingw64/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working Fortran compiler: C:/msys64/mingw64/bin/gfortran.exe
-- Check for working Fortran compiler: C:/msys64/mingw64/bin/gfortran.exe  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether C:/msys64/mingw64/bin/gfortran.exe supports Fortran 90
-- Checking whether C:/msys64/mingw64/bin/gfortran.exe supports Fortran 90 -- yes
---- Begin: CMAKE Variables
---- SYSTEM=Windows-6.1.7601, SYSTEM_NAME=Windows, SYSTEM_VERSION=Windows-6.1.7601
---- UNIX=, WIN32=1, APPLE=, MINGW=1, MSYS=1, CYGWIN=
---- BORLAND=, WATCOM=, MSVC=
---- C_COMPILER_ID=GNU, COMPILER_IS_GNUCC=1
---- End: CMAKE Variables
-- Configuring done
-- Generating done
-- Build files have been written to: C:/msys64/home/bmaggard/oca/try1/build

$ . ./run_make.sh
[ 14%]   *** Generating .def for impi.dll (gendef)
 * [C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2017.4.210\windows\mpi/intel64/bin/impi.dll] Found PE+ image
[ 28%]    ** Generating libimpa.a import library to impi.dll (dlltool)
C:\msys64\mingw64\bin\dlltool.exe: Path components stripped from dllname, 'C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2017.4.210\windows

\mpi/intel64/bin/impi.dll'.
[ 42%]     * Updating libimpi.a.stamp (touch)
Scanning dependencies of target caf_impi
[ 57%] Building Fortran object CMakeFiles/caf_impi.dir/extensions/opencoarrays.F90.obj
[ 71%] Building C object CMakeFiles/caf_impi.dir/common/caf_auxiliary.c.obj
[ 85%] Building C object CMakeFiles/caf_impi.dir/mpi/mpi_caf.c.obj
[100%] Linking Fortran static library libcaf_impi.a
[100%] Built target caf_impi



libcaf_impi.a, libimpi.a, impi.def, opencoarrays.mod end up in the build folder (-Bbuild)

$ ls -al build
total 3620
drwxr-xr-x 1 AUTH+bmaggard AUTH+Domain Users       0 Aug 26 08:40 .
drwxr-xr-x 1 AUTH+bmaggard AUTH+Domain Users       0 Aug 26 08:39 ..
-rw-r--r-- 1 AUTH+bmaggard AUTH+Domain Users    1309 Aug 26 08:40 cmake_install.cmake
-rw-r--r-- 1 AUTH+bmaggard AUTH+Domain Users   14766 Aug 26 08:40 CMakeCache.txt
drwxr-xr-x 1 AUTH+bmaggard AUTH+Domain Users       0 Aug 26 08:40 CMakeFiles
-rw-r--r-- 1 AUTH+bmaggard AUTH+Domain Users   54825 Aug 26 08:40 impi.def
-rw-r--r-- 1 AUTH+bmaggard AUTH+Domain Users  218860 Aug 26 08:40 libcaf_impi.a
-rw-r--r-- 1 AUTH+bmaggard AUTH+Domain Users 2073652 Aug 26 08:40 libimpi.a
-rw-r--r-- 1 AUTH+bmaggard AUTH+Domain Users    7227 Aug 26 08:40 Makefile
-rw-r--r-- 1 AUTH+bmaggard AUTH+Domain Users    2030 Aug 26 08:40 opencoarrays.mod



Plus - make seems correct after touch on any or all:

impi.dll
impi.def
libimpi.a
libimpi.a.stamp
libcaf.h
libcaf-gfortran-descriptor.h
opencoarrays.F90
caf_auxiliar.c
mpi_caf.c


Plus - uname -a and cmake variables seem sufficient for introspection

Minus - creation src/libimpi.a.stamp (install.sh might clean that up...)


To check for installation of x86_64 prerequisite packages:

pacman -Qi mingw-w64-x86_64-gcc-fortran
pacman -Qi mingw-w64-x86_64-gcc
pacman -Qi mingw-w64-x86_64-gcc-libgfortran
pacman -Qi mingw-w64-x86_64-gcc-libs
pacman -Qi mingw-w64-x86_64-tools-git
pacman -Qi mingw-w64-x86_64-cmake
pacman -Qi mingw-w64-x86_64-make

$ pacman -Qi mingw-w64-x86_64-gcc-fortra | grep "^error: package \'* \' was not found$"
error: package 'mingw-w64-x86_64-gcc-fortra' was not found

$ pacman -Qi mingw-w64-x86_64-gcc-fortran | grep "^error: package \'* \' was not found$"



or, preferably, due to additionally checking for MSYS2/mingw64 subsystem with "^mingw64/...", could compare to "[installed]" with:

pacman -Ss gcc | grep "^mingw64/mingw-w64-x86_64-gcc-fortran " | tail -c 12
pacman -Ss gcc | grep "^mingw64/mingw-w64-x86_64-gcc " | tail -c 12
pacman -Ss gcc | grep "^mingw64/mingw-w64-x86_64-gcc-libgfortran " | tail -c 12
pacman -Ss gcc | grep "^mingw64/mingw-w64-x86_64-gcc-libs " | tail -c 12
pacman -Ss tools-git | grep "^mingw64/mingw-w64-x86_64-tools-git " | tail -c 12
pacman -Ss cmake | grep "^mingw64/mingw-w64-x86_64-cmake " | tail -c 12
pacman -Ss make | grep "^mingw64/mingw-w64-x86_64-make " | tail -c 12


$ pacman -Ss gcc | grep "^mingw64/mingw-w64-x86_64-gcc-fortran " | tail -c 12
[installed]

$ pacman -Ss gcc | grep "^mingw64/mingw-w64-x86_64-gcc " | tail -c 12
[installed]

$ pacman -Ss gcc | grep "^mingw64/mingw-w64-x86_64-gcc-libgfortran " | tail -c 12
[installed]

$ pacman -Ss gcc | grep "^mingw64/mingw-w64-x86_64-gcc-libs " | tail -c 12
[installed]

$ pacman -Ss tools-git | grep "^mingw64/mingw-w64-x86_64-tools-git " | tail -c 12
[installed]

$ pacman -Ss cmake | grep "^mingw64/mingw-w64-x86_64-cmake " | tail -c 12
[installed]

$ pacman -Ss make | grep "^mingw64/mingw-w64-x86_64-make " | tail -c 12
[installed]

Note the package version is between the " " at the end of grep string and "[installed]", in case you need to set a minimum package version.

May not have to check for install of gcc, gcc-libs, gcc-libgfortran packages, since they install as dependencies of gcc-fortran.


pacman -Qn and pacman -Qs provide more alternatives on verifying package installation (and list only installed packages), but the -Ss method above allows for 

checking whether the package was installed for the mingw64/ subsystem (rather than msys/ or mingw32/ subsystems).

**Pull request merged**
