### PR TITLE
Urgent bugfix: Issue 342 developer test flag

### PR DESCRIPTION
**Pull request by zbeekman**
| Avg response time                 | coverage on master         |
| --------------------------------- | ---------------------------|
| ![Issue Stats][PR response img]   | ![Codecov branch][coverage]|

## Summary of changes ##

Implemented #342, an added advanced option to the CMake build to enable tests with known failures, AKA developer mode. Please add `export OPENCOARRAYS_DEVELOPER=ON` to your  `.bashrc` or `.bash_profile`/`.profile` if you are an @sourceryinstitute or @sourceryinstitute/team-opencoarrays member so that you don't have to remember to pass this flag to CMake.

## Rationale for changes ##

Homebrew has released GCC 7 and the necessitates rebuilding and repackaging (aka bottling) OpenCoarrays. However, as part of the Homebrew formula build, the build tests are run, and right now, with GCC 7 we have two known failures (`convert-before-put`---a regression of sorts---and `async_comp_alloc` a not fully implemented feature)

By adding this flag, our build tests for unimplemented features and known regressions will not be run unless specifically asked for.

See also #374 and https://github.com/Homebrew/homebrew-core/pull/13219

## Additional info and certifications ##

This pull request (PR) is a:
 - [x] Bug fix
 - [x] Feature addition
 - [x] Other, Please describe:  
   Disable developer specific compile time tests, i.e. those with known failures due to regressions or partially implemented features.

I certify that:

 - [x] I have reviewed the [contributing guidelines]
 - [x] If this PR is a work in progress I have added `WIP:` to the
       beginning of the PR title
 - [x] If this PR is problematic for any reason, I have added
       `DO NOT MERGE:` to the beginning of the title
 - [x] The branch name and title of this PR contains the text
       `issue-<#>` where `<#>` is replaced by the issue that this PR
       is addressing
 - [x] I have deleted trailing white space on any lines that this PR
       touches
 - [x] I have used spaces for indentation on any lines that this PR
       touches
 - [x] I have included some comments to explain non-obvious code
       changes
 - [x] I have run the tests localy (`ctest`) and all tests pass
 - [x] Each commit is a logically atomic, self-consistent, cohesive
       set of changes
 - [x] The [commit message] should follow [these guidelines]:
     - [x] First line is directive phrase, starting with a capitalized
           imperative verb, and is no longer than 50 characters
           summarizing your commit
     - [x] Next line, if necessary is blank
     - [x] Following lines are all wrapped at 72 characters and can
           include additional paragraphs, bulleted lists, etc.
     - [x] Use [Github keywords] where appropriate, to indicate the
           commit resolves an open issue.
 - [x] I have signed  [Contributor License Agreement (CLA)] by
       clicking the "details" link to the right of the `licence/cla`
       check and following the directions on the CLA assistant webpage
 - [x] I have ensured that the test coverage hasn't gone down and added new [unit tests] to cover an new code added to the library

## For contributors and SI team members with code review priviledges ##

 - [ ] I certify that I will wait 24 hours before self-approving via
       [pullapprove comment] or [Github code review] so that someone
       else has the chance to review my proposed changes

[links]:#
[contributing guidelines]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md
[commit message]: https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message
[these guidelines]: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[Contributor License Agreement (CLA)]: https://cla-assistant.io/sourceryinstitute/OpenCoarrays
[pullapprove comment]: https://pullapprove.com/sourceryinstitute/OpenCoarrays/settings/
[Github code review]: https://help.github.com/articles/about-pull-request-reviews/
[Github keywords]: https://help.github.com/articles/closing-issues-via-commit-messages/
[unit tests]: https://github.com/sourceryinstitute/OpenCoarrays/tree/master/src/tests/unit
[PR response img]: https://img.shields.io/issuestats/p/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square
[coverage]: https://img.shields.io/codecov/c/github/sourceryinstitute/OpenCoarrays/master.svg?style=flat-square

### CODE REVIEW

**Comment by zbeekman** [comment]
I need to update the custom bottled MPICH for gcc@6 and gcc@7 for the MacOS Travis-CI tests to work again

**Comment by zbeekman** [comment]
Assuming 35cbbbb2663d43738317acc6598b3c8acd108764 fixes the build errors (due to the homebrew formula revision bump for MPICH triggered by GCC 7 release) a timely review from @rouson or anyone else on @sourceryinstitute/team-opencoarrays would be much appreciated so that we can mint a new release and fix/update OpenCoarrays in Homebrew.

**Comment by jerryd** [comment]
The change: [your change](https://github.com/sourceryinstitute/OpenCoarrays/commit/35cbbbb2663d43738317acc6598b3c8acd108764) looks straightforward and OK

**Comment by zbeekman** [comment]
> The change: your change looks straightforward and OK

@jerryd thanks for the feedback, but I think the more substantive change (that should be reviewed) can be seen here: https://github.com/sourceryinstitute/OpenCoarrays/pull/375/files#diff-af3b638bc2a3e6c650974192a53c7291 I should have been clearer in my comment... There is still some breakage in the CI system due to some Homebrew intricacies that need to be fixed. I'm going to try re-bottling on a newer MacOS and see if I can solve the issues. Right now there are problems finding dylibs (MPICH is having trouble finding libgfortran and possibly other GCC dylibs...)

**Comment by jerryd** [comment]
LGTM after looking at the other part. ;)

**Comment by zbeekman** [comment]
LGTM

Self approving because Jerry also took a look at this and it would be good to get this out ASAP

**Comment by vehre** [comment]
I am sorry, but I have to open this issue again: I have the env-variable set in my .bashrc:
declare -x OPENCOARRAYS_DEVELOPER="ON"
but do not get the tests run. I already have restarted from scratch, i.e., deleted my build-dir and let cmake start over again. But to no avail, the testcase, here async-comp-alloc is compiled, but no run, when executing ctest .

**Comment by zbeekman** [comment]
Yes I had an error in the CMakeLists.txt... I thought I merged the fix in
last night though. Can you try pulling master and see if it is resolved
now? It seems to be working as intended on Travis-CI last time I checked.

**Comment by zbeekman** [comment]
Also, it is set in an advanced CMake cache variable so you will have to
delete the build cache and rerun CMake (or edit it via ccmake, cmake-gui or
`cmake -DRUN_DEVELOPER_TESTS:BOOL=ON`)

**Comment by vehre** [comment]
This fixed the issue for me. Thx.

**Pull request merged**
