### PR TITLE
Merge master into caffeinated-opencoarrays?

### PR DESCRIPTION
**Pull request by rouson**
Is this appropriate?  Also, is there a way to specifically reject the changes to the version-number in the PROJECT statement near the beginning of the top-level CMakeLists.txt file?

### CODE REVIEW

**Comment by rouson** [comment]
@zbeekman It appears that one way to reject the version-number changes might be to use the edit icon in the [Files changed] view to manually make the edits in the merge, but I'm not certain if the manual edits then show up as new commits or something.

**Comment by zbeekman** [comment]
@rouson I'll merge this on the command line so as to preserve the 2.0.0 version number. I probably won't get to this until tomorrow afternoon.

**Comment by zbeekman** [comment]
@rouson you've updated your user.email and the CLA issue is from commits before this, yes?

**Comment by rouson** [comment]
> On Mar 3, 2016, at 8:10 PM, Izaak Beekman <notifications@github.com> wrote:
> 
> @rouson <https://github.com/rouson> you've updated your user.email and the CLA issue is from commits before this, yes?
> 
> 


Yes.

**Pull request merged**
