### PR TITLE
installer detect Windows/invoke windows-install.sh

### PR DESCRIPTION
**Pull request by rouson**
[links]:#
[contributing guidelines]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md
[issue]: https://github.com/sourceryinstitute/OpenCoarrays/issues
[PR response img]: https://img.shields.io/issuestats/p/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square
[coverage]: https://img.shields.io/codecov/c/github/sourceryinstitute/OpenCoarrays/master.svg?style=flat-square

|  Avg response time                |  coverage on master         |
|:---------------------------------:|:---------------------------:|
| ![Issue Stats][PR response img]   | ![Codecov branch][coverage] |

## Summary of changes ##

`install.sh` now invokes `windows-install.sh` when it detects Windows Subsystem for Linux

## Rationale for changes ##

The additional automation
* Will facilitate simplifying installation documentation and workflow.
* Facilitates moving `windows-install.sh` to a lower subdirectory to reduce top-level directory clutter.

## Additional info and certifications ##

This pull request (PR) is a:

- [ ] Bug fix
- [X] Feature addition
- [ ] Other, Please describe:

### I certify that ###

- [X] I reviewed and followed the [contributing guidelines], including
      - Increasing test coverage for all feature-addition PRs
      - Increasing test coverage for all bug-fix PRs for which there
        does not already exist a related test that failed before the PR
      - At least maintaining test coverage for all other PRs
      - Ensuring that all tests pass when run locally 
      - Naming PR  to indicate work in progress (WIP) and to attach the PR
        to the appropriate bug report or feature request [issue]
      - White space (no trailing white space or white space errors may
        be introduced)
      - Commenting code where it is non-obvious and non-trivial
      - Logically atomic, self consistent and coherent commits
      - Commit message content
      - Waiting 24 hours before self-approving the PR to give another
        OpenCoarrays developer a chance to review my proposed code

### CODE REVIEW

**Comment by zbeekman** [comment]
> Facilitates moving windows-install.sh to a lower subdirectory to reduce top-level directory clutter.

👍 💯

**Comment by zbeekman** [comment]
major macOS issues on Travis-CI recently... CI jobs nearly done for this PR...

**Comment by rouson** [comment]
@zbeekman Actually, given that I tested this locally and it only affects a file that won't be tested on Travis-CI, it should be safe to merge this and I'd like to refer Dan to the other related PR, which only impacts documentation and therefore also doesn't impact any tests.  I'll merging this and the other one now.

**Comment by zbeekman** [comment]
@rouson just had a chance to look at the other PR now... I still see a few things that need clarifying. I might hold off on pointing Dan in this direction yet... for starters we should make clear that the static Makefiles are no longer distributed in release tarballs. (My fault I should have updated INSTALL.md when I made this change.) A few other typos and points of clarification that I spotted... not sure when I'll be able to take a run at this, but I'll try to get to it soonish

**Pull request merged**
